### ISSUE TITLE
scripts / styles file are not found

### ISSUE THREAD

**Issue by oriSomething** [felixrieseberg/ember-electron#1]
i'm might doing something wrong… but for some reason it's not working :cry: 

- OS X 10.10
- Ember CLI - v1.13.8

<img width="912" alt="screen shot 2015-09-19 at 00 00 33" src="https://cloud.githubusercontent.com/assets/2685242/9970985/7da23c48-5e61-11e5-9504-5966c6748300.png">

**Comment by hugoruscitti** [comment]
Hi @oriSomething, i think you need to change the ``locationType`` param to ``hash`` in order to run ember-electron.

For example, you can change the ``config/environment.js`` to some like this:

```
 module.exports = function(environment) {
     var ENV = {
       locationType: 'hash',
    [etc]
```

**Comment by oriSomething** [comment]
@hugoruscitti thanks! it worked
