### ISSUE TITLE
Unhandled 'error' event when trying to update the addon

### ISSUE THREAD

**Issue by bertatbagaar** [felixrieseberg/ember-electron#10]
Hi,

When trying to update the addon I get the following error message in my terminal:

```
events.js:85
    throw er; // Unhandled 'error' event
        ^
Error: read ECONNRESET
    at exports._errnoException (util.js:746:11)
    at TCP.onread (net.js:559:26)
```

Any idea on how I can fix this?

I am using `ember-cli v.1.13.13`

Thx in advance.

**Comment by bertatbagaar** [comment]
Well this is awkward, Ember server was running when I tried to update the addon.
Without Ember server running the update succeeded.
Sorry for the unnecessary issue.

**Comment by felixrieseberg** [comment]
Thanks for reporting though ;-)
