### ISSUE TITLE
Does this support acceptance tests?

### ISSUE THREAD

**Issue by eguitarz** [felixrieseberg/ember-electron#101]
I tried to write acceptance test for my electron app.

But it hangs when calling `visit` helper in the test. Is it possible to do acceptance test in ember-electron at all?

**Comment by drewchandler** [comment]
It is! I do a lot of acceptance testing in my ember-electron app via ember-cli and also spectron.

Could you provide please provide more info? What command are you using to run the tests? Is there any output in the javascript console? Can you reproduce this in a new barebones app?

**Comment by eguitarz** [comment]
Thanks @drewchandler 

I ran with `ember electron:test`

I have imported `ipcMain` in my app, so it's not easy to test as a web app. I commented out those electron related imports, and it works without any issue.

>I think this is solved, I did not update my electron.js in the test folder, cause one of the events couldn't be processed. I guess that's the reason cause electron stuck. If there is an error message would be great. Anyway, that's beyond this issue, so I'll close it now.
