### ISSUE TITLE
AJAX calls returning error code 0

### ISSUE THREAD

**Issue by cstolli** [felixrieseberg/ember-electron#105]
I hope I'm doing something wrong, but I cannot get an AJAX request for a static asset to load.  I have run:

`ember install ember-electron`

And seen my app load in Electron. I tweaked a few paths for my fonts and got them to load.  But I cannot figure out a way to get assets requested via Ember.AJAX or even just plain XMLHttpRequest to load.

I did notice that only my 'assets' and 'icons' directories appear in the `Sources` tab of the developer tool, are the files not getting copied in? My fonts are working, but they don't appear to be getting copied in either.

![image](https://cloud.githubusercontent.com/assets/29387/19463149/a0981098-94a6-11e6-8a0d-59edaf257ec3.png)

Has anyone else experienced this?

**Comment by drewchandler** [comment]
You need to use a file url with the full path to the file, not a relative path.

**Comment by felixrieseberg** [comment]
@drewchandler has the right idea. This has likely to do with your environment config - did you run the blueprint? Is `rootUrl` set to `null`?
