### ISSUE TITLE
dependency on node version

### ISSUE THREAD

**Issue by ericloud** [felixrieseberg/ember-electron#109]
Hi, 

just to notice that ember-electron doesn't work with node-5.5.0.
It would be interesting to add this point on your documentation (ember only need Node.js 0.12).

For me it's works fine when I updated to node-6.9.1, without i have an error during the installation:
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

Thanks for all your work,
Eric.

**Comment by felixrieseberg** [comment]
It's already in the docs - I understand that this might be bothersome to people, but I see no point in developers running lower Node versions than their users (Electron ships with the latest LTS, which is currently 6).

**Comment by ericloud** [comment]
You are right, I will add an issue to change my glasses.

Thanks,
Eric.
