### ISSUE TITLE
native package not being rebuilt against electron when packaging

### ISSUE THREAD

**Issue by gitmitch** [felixrieseberg/ember-electron#111]
I am using a native npm module ([node-keytar](https://github.com/atom/node-keytar)) as follows in my Ember app (this runs in the render process):

`const keytar = require('keytar');`

It's installed and included in my dependencies in package.json:

`"dependencies": {
    /* ... */
    "keytar": "^3.0.2"
  }`

I have no problems using the module in my app in my development environment, running it with `ember electron` or `ember electron:test --server`. However, it doesn't work in the packaged app.

I package the app with `ember electron:package`. I run the app by double-clicking it from Finder. When I take an action in the app that uses the keytar package, it doesn't work and I get this error in the dev tools console:

`Error: Module version mismatch. Expected 47, got 50.`

I can work around this issue by manually running electron-rebuild and electron-packager from the tmp/electron-build-tmp directory (edit: first have to disable the cleanup step in lib/commands/package.js and run ember electron:package):

`cd tmp/electron-build-tmp`
`npm install --save electron`
`../../node_modules/.bin/electron-rebuild`
`../../node_modules/.bin/electron-packager . --platform=darwin`

The resulting app works. I can take the action that uses keytar and it works fine with no error.

When I build the app with `ember electron:package`, I can see in the console output it rebuilding native dependencies, and I see in the code for ember-electron in lib/commands/package.js where it runs electron-rebuild (`rebuild.rebuildNativeModules(electronVersion, target)`). However, for some reason that is not enough, and I have to run electron-rebuild manually.

I noticed this [issue](https://github.com/atom/node-keytar/issues/51) in node-keytar where folks are saying they have to run electron-rebuild on postinstall. I don't understand exactly what that means or why that is. I'm wondering if this is a problem specific to node-keytar, but I don't know what it would be.

Any advice? Even if this isn't a bug in ember-electron and is instead an issue with node-keytar, I'm wondering if I can somehow employ the workaround programmatically in lib/commands/package.js, perhaps in a personal fork so as not to pollute this fine repo with the workaround.

I'm on OSX and I'm only building the 64-bit darwin platform so far.

(btw I *love* ember-electron. Thanks so much for developing and maintaining it!)

**Comment by felixrieseberg** [comment]
Hey! Yeah, I've seen and heard of troubles here before. `electron-rebuild`, and in turn `ember-electron`, tries pretty hard to determine for which version of Electron we need to rebuild (and which modules). That doesn't always work perfectly, resulting in the situation above.

:warning: However, in most cases, the user has a mismatch between which version of Electron is installed and the package.json. Pay attention to:

```
"dependencies": {
  "electron": "1.4.0"
}
"ember-electron": {
  "version": "1.4.0"
}
```

**Comment by gitmitch** [comment]
> However, in most cases, the user has a mismatch between which version of Electron is installed and the package.json

Yep! That was it. Thanks!
