### ISSUE TITLE
Working with multiple windows

### ISSUE THREAD

**Issue by gossi** [felixrieseberg/ember-electron#112]
This is more of a general question of what is the proposed way to deal with multiple windows within an application, since with electron it is possible to open mutliple windows. I did a short test and this code will do the trick:

```javascript
const {BrowserWindow} = require('electron').remote;

// .. somewhere later in the code
let anotherWindow = new BrowserWindow({
  width: 800,
  height: 600
});
```

However, what I'm interessted in is to put content into these windows and have it interact with the ember application. The window instance will let us `loadURL()` into the window, however it isn't very much connected to the ember app. I was wondering if it would be possible to route to an ember route within another windows, something like this:

```javascript
import BrowserWindow from 'ember-electron/browser-window';

// ... somewhere later in the code
let anotherWindow = new BrowserWindow({
  width: 800,
  height: 600
});

anotherWindow.transitionToRoute('my-route');
```

How likely is the chance we can get this?

If not, what would be the proposed way to load an html file and establish a connection between the main window and other windows to send messages across them?

Thanks
gossi

**Comment by gitmitch** [comment]
@gossi Each window runs in its own render process, and the main electron.js file runs in the main process. Use [ipcMain](https://github.com/electron/electron/blob/master/docs/api/ipc-main.md) and   [ipcRenderer](https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md) to communicate between them. To respond to a message from a window in the main process and ensure you are responding to the originating window that sent the message, use the event argument to your event handler. event.sender.send will send a reply.

To open new windows to a specific route, or navigate to a specific route in a window from the main process, just set the URL for the window to the desired route: "file://path/dist/index.html#/route".

**Comment by felixrieseberg** [comment]
@gitmich has the right idea here - that's exactly how you'd implement that. I'm closing this, just because his answer is spot on.

**Comment by gossi** [comment]
Wonderful, thank you guys. There is one remaining quesiton, as I'm in an electron environment, how do I get to know the path to my own `index.html` ? Like how do I get `file://<where/my/path>/index.html`? Thanks.

**Comment by luizcarraro** [comment]
Hi, @gossi , sorry to be answering  in 2017, but I was just passing by and this might be helpfull to someone else in the future. 

You could use the following:
const path                 = require('path');
const dirname              = path.resolve(path.dirname());
const emberAppLocation     = `file://${dirname}/dist/index.html`;

Regards.

**Comment by gossi** [comment]
No problem, I implemented this the last weekend and there was an `electron.js` which I could lookup ;)

**Comment by rwwagner90** [comment]
I am doing something like this:

```
 const settingsRoute = 'serve://dist#/settings';
 win.loadURL(settingsRoute);
```

We should probably work on documenting this.

**Comment by jacobq** [comment]
FWIW I wrote an `alt-windows` service to deal with this in my app. Basically it uses [`remote.getGlobal`](https://electronjs.org/docs/api/remote#remotegetglobalname) to get a reference to the `BrowserWindow` instance(s) then  proxies some basic methods like [.show()](https://electronjs.org/docs/api/browser-window#winshow) and (ab)uses [`window.postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to communicate between the windows to trigger things like `Router.transitionTo(...)`.

IIRC the tricky part was keeping everything as "one app". The service included a bit of logic to figure out whether it was running in the "main window" or not and also had to do some extra work to keep the `Store` in sync.

```js
// in main.js
global.mainWindowContainer = {};
global.auxWindowContainer = {};
// ... (the usual mainWindow setup)
global.mainWindowContainer.window = mainWindow;

const auxWindow = new BrowserWindow({
  title: '(aux window loading)',
  show: false,
  // ...
});
auxWindow.on('close', (e) => {
  if (mainWindow) {
    log('Auxiliary window was going to be closed but main window still open so hiding instead');
    e.preventDefault();
    auxWindow.hide();
  }
});
auxWindow.loadURL(`${emberAppLocation}/aux-window-default`);
global.auxWindowContainer.window = auxWindow;
```

```js
// renderer.js
const webContents = remote.getGlobal('auxWindowContainer').window.webContents;
await webContents.executeJavaScript(`window.postMessage(${JSON.stringify(messageForAux)})`);
```

**Comment by rwwagner90** [comment]
@jacobq what advantages does that setup have to just doing something like ` win.loadURL(settingsRoute);`?

**Comment by jacobq** [comment]
> @jacobq what advantages does that setup have to just doing something like ` win.loadURL(settingsRoute);`?

Admittedly, I didn't do a good job demonstrating/explaining above and it could certainly be improved upon (e.g. using the IPC API), but one of the problems I ran into with just using `loadURL` was that it meant waiting for the whole app to boot up again rather than being instantly ready. In my case, one of the routes has a "helper" window that I wanted to hide automatically whenever leaving that route. The route used by that window also had UI controls that affected settings in the store that I wanted it to tell the other window about immediately.

**Comment by rwwagner90** [comment]
@jacobq so `loadURL` reloads the app? Even if it is pointed to a route of the existing app? I thought what I had was just navigating to the route, not reloading the app.

```js
 const settingsRoute = 'serve://dist#/settings';
 win.loadURL(settingsRoute);
```
