### ISSUE TITLE
Attempted to load extension "Ember Inspector" that has already been loaded.

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#122]
I see the same error as #104 every time an automatic code refresh happens. 

### Steps to reproduce

- `ember init`
- `ember install ember-electron`
- `ember electron`
- Change content of `application.hbs` or any other file and save to trigger code refresh

### Expected behaviour

- Ember Inspector should be injected only once

### Observed behaviour

- Ember Inspector gets injected on each refresh, both automatic and manual

If someone can point me to the place where the Inspector gets injected, I'll try to fix this myself and provide a pull request. However at first glance I'm not sure where to start.

**Comment by pichfl** [comment]
I think I found the corresponding code in `app/electron/reload.js`. I'll make an attempt at fixing this this week and file a pull request.

**Comment by kevingelion** [comment]
Hey @pichfl I'm experiencing the same thing - did you make any progress on this?

**Comment by pichfl** [comment]
Sadly no. We use electron for a small internal project and my attempt didn't work out and I had not much time since then.

**Comment by felixrieseberg** [comment]
Hey! Thanks for reporting, but no worries - this is (currently) how Electron works. It's not *actually* being injected multiple times - Electron is simply saying "Yup, got it, no worries".

It *is* clearly annoying though, so Electron recently added this beauty - https://github.com/electron/electron/pull/5965 - I'd gladly take a PR!

**Comment by pichfl** [comment]
This PR here should give good directions: https://github.com/sindresorhus/electron-debug/pull/40/files

I'll try to make a PR soonish, but I'm swamped, so @kevingelion if you or anyone is faster with this, feel free to do it.

**Comment by kevingelion** [comment]
Sure, I'll probably have some time in the next couple days 😄

**Comment by pichfl** [comment]
@felixrieseberg PR #139 now matches the projects code style and actually does the right thing.
