### ISSUE TITLE
issue with require('electron') in ember electron controller

### ISSUE THREAD

**Issue by premingiet** [felixrieseberg/ember-electron#124]
when i try to use 
const electron = require('electron');
in the controller section of the app, then when i save it, in the command window, it gives an error require is not defined, but app builds and works fine. 

Also, like in this below example code

import Ember from 'ember';
export default Ember.Controller.extend({

	actions: {

    	center() {
    			        const {remote} = require('electron');
				const {BrowserWindow} = remote;
				const win = BrowserWindow.getFocusedWindow();
      				win.center();
    		     }
});

then it gives me error as "require is not defined"

But if i use 
const {remote} = window.require('electron');

then it gives me no error, and why is that ?
if i want to import ipc module, then i can do it.

How can i directly use like 
const electron = require('electron');
and not to get any error in command window ?

I use 
ember-cli: 2.10.0
node 6.9.2
os: win32 x64
ember-electron version: 1.12.1

**Comment by bendemboski** [comment]
That's just a linting issue -- do you use jshint or jscs or eslint? By default, `require` isn't available in browsers, so your linter is telling you that it doesn't think it's defined. So you need to tell it that `require` is a global, which you can do in the linter's config file, or at the top of the file in which you reference it you can put `/* global require */`.

**Comment by premingiet** [comment]
no i haven't used any of them jshint or jscs or eslint. I am kind of new to ember and electron, 

But after writing 
global require
on top of the file in controller section of my app, now it doesn't get build, and it throws a bunch of error

where am i wrong ?
my sample code now looks like

import Ember from 'ember';
global require;
export default Ember.Controller.extend({

actions: {

	center() {
			const {remote} = require('electron');
			const {BrowserWindow} = remote;
			const win = BrowserWindow.getFocusedWindow();
  				win.center();
		     }
});

**Comment by bendemboski** [comment]
jshint is turned on by default when you set up an ember project. You need it all the way at the top, and it needs to be a comment. So you want:

```javascript
/* global require */
import Ember from 'ember';
export default Ember.Controller.extend({

  actions: {
	center() {
			const {remote} = require('electron');
			const {BrowserWindow} = remote;
			const win = BrowserWindow.getFocusedWindow();
  				win.center();
		     }
  }
});
```

**Comment by premingiet** [comment]
thanks a lot ! it totally fixed the issue !
Now i can use require as normal.....
since i am using sublime text, so i have now installed sublime linter with jshint. it really helps a lot !
thanks
