### ISSUE TITLE
cannot fetch json data from remote url after packaging ember electron app

### ISSUE THREAD

**Issue by premingiet** [felixrieseberg/ember-electron#125]
I am new to electron and ember....

before packaging the ember electron app, i tried to fetch some json data from url and it worked fine
below is sample code that is used in controller section of app

json() {
		var request = require('request');
		var url = 'http://www.omdbapi.com/?i=tt0944947&Season=1';
                request.get({
    							url: url,
    							json: true,
    							headers: {'User-Agent': 'request'}
  							}, (err, res, data) => {
    				if (err) {
      							console.log('Error:', err);
      							document.getElementById("io").innerHTML = err;
    				} else if (res.statusCode !== 200) {
      						console.log('Status:', res.statusCode);
      						document.getElementById("io").innerHTML = res.statusCode;
    				} else {
      						// data is already parsed as JSON:
                  for (var i = 0; i <= data.Episodes.length - 1; i++) {
                    document.getElementById("io").innerHTML += '<h5>'+data.Episodes[i].Title+'</h5></br>';
                                   }
    			      }
			});
    		   },

but as soon as i packaged the app with "ember electron:package --platform win32" the build was successful without any error, but i can no longer fetch any json data when i click the button.

**Comment by felixrieseberg** [comment]
You're probably running into cross-origin issues. You can find more information here: https://www.html5rocks.com/en/tutorials/cors/.

However, [you might want to adapt your code to just use `fetch` in `no-cors` mode](https://developers.google.com/web/updates/2015/03/introduction-to-fetch?hl=en), which will fix all your issues.
