### ISSUE TITLE
Electron Deprecation: The version parameter is deprecated, use electronVersion instead

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#126]
When I use `ember electron:package darwin` I see the following warning:

> You are using the old API, please read the new docs and update to the new API
> The version parameter is deprecated, use electronVersion instead

**Comment by anulman** [comment]
Thanks @pichfl. Closing this, as #129 uses a static version on `electron-prebuilt-compile` to determine electron version
