### ISSUE TITLE
"ember electron:package --platform darwin" does not produce app running ember.js

### ISSUE THREAD

**Issue by maxigs** [felixrieseberg/ember-electron#127]
I just tried to create an application with ember-electron.
The development version via `ember electron` runs fine, but i can't package a running app.

It always just shows a blank page, as if ember does not start.

I also tried with a minimal new app:

`$ ember new ember-quickstart`
`$  cd ember-quickstart`
`$ ember install ember-electron`
`$ ember electron`
-> running fine, showing the ember welcome page

`$ ember electron:package --platform darwin`
-> running the app build in "electron-builds/..darwin/..app" just shows a blank page

Am i doing something wrong here?
How can i debug this?

**Comment by maxigs** [comment]
Same with the windows build, so i guess it's a general packaging issue.

It looks like i just start a empty browser, no ember-app there at all.
Do i need to add the `dist` directory to the `package.json` or miss any other step?

**Comment by pichfl** [comment]
Seems welcome page is rather special and didn't work for me either.

Have you tried replacing `{{ember-welcome-page}}` with something like `<h1>Foo</h1>` in your `application.hbs`?

**Comment by maxigs** [comment]
I first tried with a whole little app i wrote, and only went to try with the welcome page as the other didn't work.

Just tried by changing the application.hbs to "hello world", no result either.

I also added some text in the index.html file, does not show up also. So it's not just the ember.js not starting up, but it does not even load the index.html in the first place.

**Comment by pichfl** [comment]
What happens when you run `ember electron` without packaging? Any errors or warnings there? Also which versions are you running? Can you post `npm list --depth=0` here?

**Comment by maxigs** [comment]
Thanks for helping me out @pichfl !

`$ ember electron`:
```
Build successful - 1011ms.



Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (16)                                    | 524ms (32 ms)
Concat (8)                                    | 237ms (29 ms)

--------------------------------------------------------------------
Ember Inspector running on http://localhost:30820
Open the inspector URL in a browser to debug the app!
The inspector is also available as an addon inside your
app's developer tools.
--------------------------------------------------------------------
Starting Electron...
--------------------------------------------------------------------
```

App starts fine and displays content as expected.


`$ npm list --depth=0`

```
npm list --depth=0
ember-quickstart@0.0.0 /Users/maxigs/Projects/Tickaroo/ember-quickstart
├── broccoli-asset-rev@2.5.0
├── devtron@1.4.0
├── electron@1.4.15
├── electron-packager@8.5.1
├── electron-rebuild@1.5.7
├── ember-ajax@2.5.3
├── ember-cli@2.11.0
├── ember-cli-app-version@2.0.1
├── ember-cli-babel@5.2.1
├── ember-cli-dependency-checker@1.3.0
├── ember-cli-htmlbars@1.1.1
├── ember-cli-htmlbars-inline-precompile@0.3.6
├── ember-cli-inject-live-reload@1.6.1
├── ember-cli-jshint@2.0.1
├── ember-cli-qunit@3.1.0
├── ember-cli-release@0.2.9
├── ember-cli-shims@1.0.2
├── ember-cli-sri@2.1.1
├── ember-cli-test-loader@1.1.1
├── ember-cli-uglify@1.2.0
├── ember-data@2.11.0
├── ember-electron@1.12.1
├── ember-export-application-global@1.1.1
├── ember-inspector@2.0.4
├── ember-load-initializers@0.6.3
├── ember-resolver@2.1.1
├── ember-source@2.11.0
├── ember-welcome-page@2.0.3
└── loader.js@4.1.0
```

(after clearing the `electron-builds` dir)

`$ ember electron:package`:

```
cleaning up...
Built project successfully. Stored in "./tmp/electron-build-tmp/dist".

Copying files into Electron Build folder
Copying electron.js
Copying package.json
Installing production dependencies into Electron Build Package
Installing Electron headers for version 1.4.15
Recompiling native dependencies
You are using the old API, please read the new docs and update to the new API
The version parameter is deprecated, use electronVersion (or --electron-version in the CLI) instead
Packaging app for platform linux ia32 using electron v0.37.5
Packaging app for platform win32 ia32 using electron v0.37.5
Packaging app for platform darwin x64 using electron v0.37.5
Packaging app for platform linux x64 using electron v0.37.5
Packaging app for platform mas x64 using electron v0.37.5
Packaging app for platform win32 x64 using electron v0.37.5
Packaging app for platform linux armv7l using electron v0.37.5
```

**Comment by anulman** [comment]
@maxigs Resolved? OK to close?

**Comment by maxigs** [comment]
@anulman feel free to, but i have no solution to add, as i haven't continued on the project since :(
