### ISSUE TITLE
Ember-Electron not packaging under Windows

### ISSUE THREAD

**Issue by danidr** [felixrieseberg/ember-electron#130]
Hello,
I have been using Ember-Electron for the past month and so to develop a specific application.
While I have been developing using Linux, my application is supposed to run under Windows, so I have been moving all the codebase (via GitHub) to a Windows 10 development machine.
When I run the app via `ember electron` in Windows, it currently launches in development environment and functions correctly. When I decide to package it, though, the process sits on `runTopLevelLifecycles: sill install printInstalled`. I have tried leaving it work for hours and hours, but it never gets past that step.
On Linux though, the app runs and compiles without a problem.
Has anyone faced the same issue? Is there a way to get a more verbose output from `ember electron:package`?
Thank you in advance,

Daniele

**Comment by Nortrem** [comment]
Have the same problems with `ember electron:package --platform=win32` on Windows 10 
Still don't know how to fix it.

**Comment by debelop13** [comment]
I have the saaame problem with win7 and win10!!

**Comment by Rodrigo-O** [comment]
Hi!
I have the same problem and find a way to fix it, but first of all, my english is bad, and i probably do more steps that needed (new to ember, electron, npm, node and all js world), but in my case this works:

I have Win8.1 64b, and when force --arch=ia32 (and some workarround in the middle of the process), it finally works.

1. cd to the project and exec `npm set npm_config_arch ia32`

2. `npm install --arch=ia32 ember-electron --save-dev` (i have previously uninstalled it via npm)

3. i use the ember generator `ember  g ember-electron`

4. and then reinstall the packages  `npm install --arch=ia32 electron electron-packager electron-rebuild ember-inspector devtron`

5. finally run the packaging `ember electron:package --platform=win32 --arch=ia32`

6. and here is when i have the workarround, it fails with the following:

> Built project successfully. Stored in "./tmp/electron-build-tmp/dist".
> 
> Copying files into Electron Build folder
> Copying electron.js
> Copying package.json
> Installing production dependencies into Electron Build Package
> Recompiling native dependencies
> 
> Native compilation did not work:
> Error: ENOENT: no such file or directory, scandir '[path_to_project]\tmp\electron-build-tmp\node_modules'

to continue, manually create an empty node_modules folder in that path and rerun  `ember electron:package --     platform=win32 --arch=ia32`

7. it works! : 

> cleaning up...
> Built project successfully. Stored in "./tmp/electron-build-tmp/dist".
> 
> Copying files into Electron Build folder
> Copying electron.js
> Copying package.json
> Installing production dependencies into Electron Build Package
> Recompiling native dependencies
> Packaging app for platform win32 ia32 using electron v0.37.5

Hope it helps in the meanwhile

**Comment by anulman** [comment]
@danidr would you be able to test against the 2.0 beta (i.e. against master)? Curious if this is resolved by using electron-forge.

Instructions are in the **FYI** section of #147

**Comment by kevingelion** [comment]
I had a similar issue where it would get stuck while building for Windows on Windows at `Compiling native dependencies` using `1.x`.

Using `2.beta`, packaging is working for all platforms 😄

**Comment by anulman** [comment]
Haha thanks @kevingelion! Three.js though... 😉 

@danidr @Nortrem @debelop13 I'm going to close this issue for now as I imagine this is resolved in the beta. If you're still having trouble, please please please comment and I / we'll reopen.

(Also, if you need any support installing / setting up beta, feel free to post in #e-electron on the Ember.js Slack group, or ping me directly there @anulman)

**Comment by VsevolodTrofimov** [comment]
v 2.0 doesn't start on windows due to multiple platform specific (mac) dependencies.
yarn decines to install it, installing with npm downloads multiple files that would not run.

**Comment by pichfl** [comment]
@VsevolodTrofimov I separated your problem into #168 as it doesn't exactly refer to packaging apps but the installation of the addon itself.
