### ISSUE TITLE
Unable to set icon for darwin platform

### ISSUE THREAD

**Issue by GiovanniL19** [felixrieseberg/ember-electron#132]
Hi, 

I am trying to set the icon for the darwin platform, the icon I have is a  `.icns` which has been converted from a png at [cloudconvert](https://cloudconvert.com/png-to-icns)

In my package.json I have:
`"icon": "assets/icons/main"`

Any ideas what I'm missing?

Thank you in advance

**Comment by GiovanniL19** [comment]
Realised where I went wrong, needed the following path in the package.json

`"icon": "public/assets/icons/main"`

**Comment by GiovanniL19** [comment]
The icon is set to the application all okay. However, as soon as you put the application in the `applications` directory on Mac, and go to the launcher, the icon is missing?

**Comment by pichfl** [comment]
The easiest way to do this is to create a folder for electron assets besides the ember application.

I added a `/assets` folder next to `/app` and added it and it's contents to the `copy-files` directive in `package.json` like this:

```json
...
"copy-files": [
      "electron.js",
      "package.json",
      "assets/**/*",
    ],
...
```

No you can reference the icon by `/assets/icons/main.icns`. The extension is required, both in the path and the actual file, double check if it is missing.

The reason to go this way is that the public folder gets copied by ember-cli into `/dist` which is by default the only folder copied by ember-electron (afaik). This changes the path for your icon from `/public/...` to `/dist/...` in the packaged build. Using a separate folder solves this without copying over the resources twice which would happen if you chose to add the public folder to copy-files directly.

**Comment by GiovanniL19** [comment]
Hi @pichfl 

Thank you for your comment! I have made these changes and the icon is set to the application. However, when I move the app to the applications directory on the mac. The launcher doesn't show the icon...

<img width="220" alt="screen shot 2017-02-06 at 16 10 12" src="https://cloud.githubusercontent.com/assets/10454722/22655105/ea9f962e-ec86-11e6-886f-ee43afa262d7.png">

**Comment by pichfl** [comment]
Your right. I just compiled our project again from a fresh copy and the icon does not show.

**Comment by pichfl** [comment]
I just tried it with our project and https://github.com/TryGhost/Ghost-Desktop/blob/master/assets/icons/ghost.icns which worked fine when I put the icon straight in the root of the repo and used `"icon": "ghost",` in the package.json. Maybe there is something wrong with the .icns?

**Comment by pichfl** [comment]
Maybe https://github.com/TryGhost/Ghost-Desktop/blob/master/assets/icons/make-iconset.sh can help to create a compatible icon.

**Comment by GiovanniL19** [comment]
Perfect, thank you very much @pichfl. It was the .icns that was causing the issue. I ended up creating a new icon in Sketch and used a plugin called [Export More](https://github.com/nathco/Export-More). Works like a charm, thanks again!
