### ISSUE TITLE
ember electron:build removes cursor in terminal

### ISSUE THREAD

**Issue by halfbyte** [felixrieseberg/ember-electron#133]
This is somewhat of an annoyance: Whenever I run said command, my cursor is gone and can only be restored by a `reset` or by doing an `echo "\u001b[?25h"`.

I've tried to look at the build command and I can fix the bug by inserting `this.ui.stopProgress()` into the [cleanup](https://github.com/felixrieseberg/ember-electron/blob/8c1f936b5c8cd09a8612083926c70a8b68c67e84/lib/commands/package.js#L361) function.

I'm not sure this is the correct fix, though. I tried to remove the `startProgress` call from the [build()](https://github.com/felixrieseberg/ember-electron/blob/8c1f936b5c8cd09a8612083926c70a8b68c67e84/lib/commands/package.js#L175) function, but that doesn't fix it, so maybe there are other occasions where something like `startProgress` is called. 

In any case, looking at the code of `startProgress` and the underlying ora code, calling startProgress without a corresponding `stopProgress` is probably not a good idea.

**Comment by felixrieseberg** [comment]
Hey, thanks for the issue and the research! Here's my take: I agree that we should have the `stopProgress` and if it fixes an annoyance for you, it deserves to be in. Want to file a quick PR? I'd hit ✅ on it right away :tada:
