### ISSUE TITLE
ember electron:package fails to install npm modules

### ISSUE THREAD

**Issue by kevingelion** [felixrieseberg/ember-electron#135]
Getting my app running in electron was a breeze until packaging the app (only took 2 minutes to find a workaround) but here's what's going on:

I ran `ember electron:package` and got:  
```
Copying files into Electron Build folder
Copying electron.js
Copying package.json
Installing production dependencies into Electron Build Package
Recompiling native dependencies

Native compilation did not work:
Error: ENOENT: no such file or directory, scandir '/Users/kevin/Desktop/electron-dashboard/tmp/electron-build-tmp/node_modules'
```

My workaround was to cd into `electron-dashboard/tmp/electron-build-tmp/` and run `npm install` then ran `ember electron:package` again and everything worked fine.

**Comment by bendemboski** [comment]
Duplicate of #131 no?

**Comment by kevingelion** [comment]
Ah, yep. Sorry!
