### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/ember-electron#14]
- [x] Packaging
- [ ] Installers
- [x] Ember Best Practices

**Comment by Frozenfire92** [comment]
Maybe some common paradigms (running a node server with your app for example)

**Comment by timmyomahony** [comment]
+1 Having arrived at Electron from Ember, it's hard to see how to get everything working. A simple demo application would be great

**Comment by jacobq** [comment]
Not sure if this belongs in this issue or somewhere else, but as part of the 2.x work I think the [defining files to package](https://github.com/felixrieseberg/ember-electron#defining-files-to-package) section of the `README.md` needs to be updated to show the new location of `electron.js` and perhaps also [`.compilerc`](https://github.com/felixrieseberg/ember-electron/issues/147#issuecomment-283833558).

**Comment by anulman** [comment]
@felixrieseberg @timmyomahony @jacobq closing this due to stale; documentation planning & progress will be tracked in #328
