### ISSUE TITLE
Ember Inspector: Ember application not detected!

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#140]
I just started another fresh project and it seems that Ember Inspector inside the Developer Tools is not detecting any Ember Application.

I'm using
Ember: 2.11.2
Ember Data: 2.11.1
Ember Inspector: ^2.0.4
Ember Electron: 1.12.6

If I use the regular `ember server` command, the inspector works as expected.

**Comment by pichfl** [comment]
If seems that the way the remote `getRemoteDebugSocketScript` or the way `ember_debug.js` is injected in development mode interferes with the normal Ember Inspector instance. I will continue to investigate.

**Comment by anulman** [comment]
1) Do you have any conflicting procs listening on port 30820?
2) Can you confirm this happens all the time? Sometimes I find I need to reload the page to get it working, weirdly

**Comment by pichfl** [comment]
1. Nothing on that port - checked with `lsof -i tcp:30820` (on macOS)
2. Testing in two different projects, happening consistently. Both projects are private, but I can try to give you access to one of them if that helps in any way.

If I can provide any more details or anything, just tell me.

**Comment by anulman** [comment]
Last one—do you have Mirage installed?

**Comment by pichfl** [comment]
Nope. Neither app uses complex models, so Mirage isn't needed yet. I'm working on these apps to evaluate Electron for a bigger project, so having Mirage there in the future would be rather useful though.

**Comment by pichfl** [comment]
Just to mention it: When I remove the remote debugging script injection it works.

**Comment by anulman** [comment]
[moves to Slack; @pichfl or I will post back here once resolved]

**Comment by nahtnam** [comment]
@pichfl How do you remove remote debugging script injection?

**Comment by pichfl** [comment]
@nahtnam @anulman and I will probably have a proper fix ready soon.

Here is a way to quickly hack this together:

1. clone this repo or make a fork and clone that, probably at https://github.com/felixrieseberg/ember-electron/tree/v1.12.7 
2. Go to https://github.com/felixrieseberg/ember-electron/blob/v1.12.7/lib/helpers/remote-debug-script.js
3. return an empty string instead of the string template
4. use yarn link or npm link to link the repo to your local project. 
5. proceed with caution.

**Comment by anulman** [comment]
Update for clarity: this is not related to the remote inspector, only the in-proc inspector. `http://localhost:30820` works as expected in a browser; however the Ember tab added to the embedded browser's dev tools cannot find the app.

**Comment by pichfl** [comment]
This will be solved by #148
