### ISSUE TITLE
shim-head and shim-footer should only be injected if running in Electron

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#141]
As of today, ember-electron pollutes the index.html even for regular builds of the application using `ember build`. 

**Expected behaviour**
The require / requireNode shims should only be included if the application is running inside of Electron.

Basically wrapping the whole contentFor() method in index.js in a suiting conditional should do the trick.

**Comment by anulman** [comment]
👍 I like. Okay if we wait until #129 is merged?

Also, think you could write this PR?

**Comment by pichfl** [comment]
Yes and yes.
