### ISSUE TITLE
Adopt Ember project codestyle

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#143]
Ember is switching away from JSHint to ESLint and now provides plugins for a more consistent code style.

To my understanding this project deviates from typical ember addons and uses StandardJS, which is as of now not quite prepared to handle modern JS syntax used by Ember (let/const, arrow functions, etc are still topics to be discussed by its maintainers).

My suggestion is to follow the code style of the ember project. Since this is mostly cosmetic, I would be happy to provide a PR if you like the idea, or just shut up if you don't. 😁

**Comment by anulman** [comment]
+1. @felixrieseberg?

**Comment by felixrieseberg** [comment]
Into it! Let's merge the current electron-forge work so we got a clean slate to start the work. @pichfl, a PR would be extremely welcome <3!

**Comment by pichfl** [comment]
Will do 🙂

**Comment by bendemboski** [comment]
#120 will cause you some merge headache also if you do this off of master. I think it's ready to merge, but I'm hesitating because of failing unit tests in master... @felixrieseberg should I just go ahead and merge? I *think* it all works...

**Comment by pichfl** [comment]
I'll wait for #120 then.
