### ISSUE TITLE
Provide upgrade tooling for 1.x => 2.x

### ISSUE THREAD

**Issue by anulman** [felixrieseberg/ember-electron#147]
Upgrading from 1.x => 2.x will change two major expectations:

1) `electron.js` should live in `ember-electron/main.js` (vs. main dir); and
2) `ember-electron` config in package.json should be removed, and replaced with a JSON or JS file at `ember-electron/.electron-forge`, matching [config spec from the electron-forge project](https://github.com/electron-userland/electron-forge#config)
3) Remove the `main: electron.js` line from your package.json

High-level, we ought to help users handle this with a blueprint. Options are as follows, please vote with the corresponding reaction emoji / comment with a comment:

- 👍 With `ember g ember-electron`, detect a 1.x app by virtue of `electron.js` living in the top-level dir; move electron.js; and automatically migrate the right variables in package.json;
- 🎉 Add `ember g ember-electron upgrade`, throw if it's not a 1.x app; move electron.js and automatically migrate the right variables in package.json; or
- ❤️ With `ember g ember-electron`, detect a 1.x app by virtue of `electron.js` living in the top-level dir; warn user they are upgrading and link to instructions (and/or recommend using `ember g ember-electron upgrade`?)

##### FYI
Just ran through the flow with @kevingelion on `master` as of this writing; if you've got a 1.x project and would like to try running 2.x you can:

1) `rm -rf node_modules/`
2) switch `ember-electron` to point to `github:felixrieseberg/ember-electron`
3) run `npm install`
4) clone `isleofcode/electron-forge`, check out `feat/make-platforms`, `npm install`, then `npm link` it in your ember project folder
5) run `ember g ember-electron`

**Comment by anulman** [comment]
One note from a debug session with @kevingelion: if we move the `electron.js` on the user's behalf, it risks borking relative paths. If we _do_ move the file for the user, we can theoretically inspect it and adjust relative requires accordingly; else we ought to at least throw a big warning

**Comment by pichfl** [comment]
I think it's wise to print a warning if we find a electron.js in the root. Automatically moving it comes with many risks and doing it manually forces the user to check for other problems as well. 

Regarding the electron forge dependency: can't we link to the branch in package.json while in beta?

**Comment by anulman** [comment]
@pichfl can you elaborate on perceived risks re: moving electron.js? Hoping we can air out likely scenarios as part of this decision.

Re: including in package.json: last time I tried that, it caused several problems with the forge install. That may have just been my env though; if you've had a different experience then that would be my preference too 👍

**Comment by pichfl** [comment]
Relative paths as a single string would be quite easy to detect, but how about stuff like `path.join(__dirname, 'dist', 'something.icns')` or similar, which is not that rare when you try to add and change a tray icon and other assets? 

Re package.json: Will try when I'm back in the office.

**Comment by anulman** [comment]
_n.b. Updated items 2 & 3 in first msg per debugging with @kevingelion_

**Comment by anulman** [comment]
Note to self: we should also include a gitignore in ember-electron dir, to ignore contents of `out`

**Comment by anulman** [comment]
Note to self: consider including compilerc in ember-electron dir; will need to include it in default package.json copy-files

**Comment by jacobq** [comment]
@anulman sorry to bother you, but I would like to try previewing the 2.x/master code and am getting stuck. Could you explain the "nvm link" step mentioned above? Is [`nvm`](http://nvm.sh/) required? (I don't have it installed.) On POSIX systems can a symbolic link be used instead, i.e. `ln -s ../electron-forge .`? I tried the latter but then `ember g ember-electron` seems to have gotten stuck on the `Installing electron build tools` step. The spinner has been going round and round for 30+ minutes but CPU, disk, and network interfaces all appear very idle. (Env is Debian Linux 4.9 x64, node v6.10.0, npm v3.10.10)

**Comment by anulman** [comment]
@jacobq derp, that's supposed to be `npm link`. Fixing...

**Comment by kevingelion** [comment]
yeah... that's probably my fault. sorry! 

@jacobq clone `electron-forge` somewhere external: `git clone git@github.com:isleofcode/electron-forge.git`, `git checkout feat/make-platforms`, `npm link` (this automatically runs install scripts), `cd <ember-electron project`, `npm link electron-forge`

**Comment by anulman** [comment]
@kevingelion did you mean `npm install` for that first `npm link`?

Also, the second `npm link` should probably be `npm link path/to/cloned-electron-forge`

**Comment by jacobq** [comment]
Ahh, thanks for the help guys. That explains why it wasn't working. (Though I feel a bit sheepish for never having used `npm link` before.) It looks like this command will modify my system (i.e. require root privileges). Is there any way to do it w/o that, such as modifying my `PATH`?

**Comment by kevingelion** [comment]
@anulman the first `npm link` automatically runs the install scripts - nothing wrong with `npm install && npm link`, though.

regarding specifying the path, yeah it's probably a good habit to do. i only linked one instance of it so it automatically detects the path.

@jacobq might be worth using `nvm` since your links will be per version of `node`/`npm` you're using.

**Comment by anulman** [comment]
@jacobq I've not seen the root privileges requirement before; is this because you're using a global / sudo-installed version of node?

**Comment by jacobq** [comment]
@anulman that's probably why; my bad. I'll worry about fixing that later as it looks like it just wanted to write to a directory that's for node anyway. However, after going through all this I get the following error:
```
error macos-alias@0.2.11: The platform "linux" is incompatible with this module.
error Found incompatible module
```
Looks like this is upstream: https://github.com/electron-userland/electron-forge/issues/136

**Comment by anulman** [comment]
Indeed it does. Are you using yarn?

**Comment by jacobq** [comment]
@anulman Not on purpose, but I do have it installed on my system. I will try uninstalling it once (unless you know an easier / less drastic way).

**Comment by jacobq** [comment]
OK, uninstalling `yarn` allowed me to successfully re-generate the blueprint. Now I have two `electron.js` files though: the pre-existing one in the project root (which appears to still be run with `ember electron`) and a newly generated one in `ember-electron/`. Based on reading previous discussions I'm going to try moving the pre-existing one into that folder (overwriting the new one), adjusting paths, etc. as needed. Thanks again for your help.

**Comment by anulman** [comment]
Nice! Glad to hear that worked out. One extra note (it burned me when making a demo app earlier): please make sure that .compilerc is included in your copy-files too

**Comment by pichfl** [comment]
If you want to use a local version of ember-electron, see [my comment](https://github.com/felixrieseberg/ember-electron/issues/160#issuecomment-284005502) in #160

**Comment by debelop13** [comment]
Sorry for my question, but how can I switch ember-electron to point to github:felixrieseberg/ember-electron? Thanks

**Comment by pichfl** [comment]
`npm install felixrieseberg/ember-electron`

**Comment by jacobq** [comment]
@debelop13 you can also adjust your `package.json`'s dependencies to use a format described here:
https://docs.npmjs.com/files/package.json#git-urls-as-dependencies

**Comment by anulman** [comment]
Once #170 lands we should revisit this

**Comment by parm-ameotech** [comment]
![error](https://cloud.githubusercontent.com/assets/7523068/24694527/f11d7b1e-19ff-11e7-96e6-b1b54eb74b9e.png)

I am using master of ember electron 2.0 but when I am building a package it is giving me very strange issue. Please help I am not sure how to fix it.

**Comment by anulman** [comment]
Realized the notes in the top comment were a bit out of date. @parm-ameotech are you coming from a 1.x app? If so, please confirm:

- Have you moved your `electron.js` file to `ember-electron/main.js`?
- Have you removed the `main` line from package.json?
- Have you run `ember g ember-electron`, which installed deps like `electron-prebuilt-compile` into your package.json?
- Have you moved all relevant config from your package.json to the generated `.electron-forge` file?

Thanks!

**Comment by parm-ameotech** [comment]
@anulman Thanks! for the reply but I make it work on linux machine. It think its better to use linux rather than windows.

**Comment by debelop13** [comment]
Hi!

Upgrading from 1.0 to 2.0 I have problems with ES6..

There are 'requires' in my ember project.. like - require("electron").electron.webFrame.setZoomLevelLimits(1, 1); -
And is giving this error - Property object of MemberExpression expected node to be of a type ["Expression"] -

I change it for:
import {webFrame} from 'electron';
electron.webFrame.setZoomLevelLimits(1, 1);

Then, build is successful but index.html is not showing, and in console i have this eror Uncaught Error: Cannot find module 'myproject/routes/index'

And I don't understand why..
