### ISSUE TITLE
Define options in package.json or similar file

### ISSUE THREAD

**Issue by Jordan4jc** [felixrieseberg/ember-electron#15]
Is there currently a way to define all those options in the `package.json` or another file? I looked at the docs for the `electron-packager` and didn't see anything like that, it would be really helpful to be able to do that rather than having to have the options in a notepad somewhere and copy and past them each time I want to make a package.

**Comment by felixrieseberg** [comment]
Really fair point - makes a lot of sense. I'll add that tomorrow!

**Comment by Jordan4jc** [comment]
🙌
