### ISSUE TITLE
Sending headers to an API

### ISSUE THREAD

**Issue by mk-conn** [felixrieseberg/ember-electron#150]
Not sure if this is an ember-electron related issue...  

In my ember adapter I set an authorization header which works with no problems (running the ember app in a web browser)
```javascript
headers: Ember.computed(function () {
        const config = get(this, 'configuration').retrieve('conn');
        if (config) {
            const auth = btoa(config.username + ':' + config.password);
            Ember.debug(`adapter: application::headers() auth:${auth}`);

            return {
                Authorization: 'Basic ' + auth
            };
        }

    }).volatile(),
```

Running in ember-electron the header is not set... Do I have to do this differently in ember-electron?

**Comment by anulman** [comment]
Not typically, and none of your code seems particularly "off".

Have you dropped in a debugger / `console.log` statements yet to check state as the fn executes? I'd be most interested in e.g. what the `configuration` & `conn` objects are / how they're built.

**Comment by mk-conn** [comment]
`configuration` is a service that stores username + password settings in the localstorage... nothing fancy. And debugging shows, that those values are correct

**Comment by pichfl** [comment]
Is there a reason that those computed properties are marked as volatile? Have you tried using DS.PromiseProxy to wrap the calls to your configuration service and make the computed keys dependent? 

.volatile works a bit different than one might expect. It means it no longer notifies of changes automatically, see docs here: http://emberjs.com/api/classes/Ember.ComputedProperty.html#method_volatile (at least for me, that was exactly the opposite of what I expected)

**Comment by mk-conn** [comment]
Hmm.. okay, I'm checking this volatile thing - can't really remember why I did it that way...

**Comment by anulman** [comment]
@mk-conn was this resolved?

**Comment by mk-conn** [comment]
Nope, changed to not using volatile() but it didn't make any difference. Also tried to use the promise but couldn't make it really work in the headers() method...

**Comment by mk-conn** [comment]
I'm using ember-electron 2  - now its working! :)
