### ISSUE TITLE
Update blueprints to match new code style

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#153]
Seems I forgot quite a few files.

- [x] index.js
- [x] files/tests/electron.js
- [x] files/ember-electron/electron.js
- [ ] files/config/environment.js // I'm not quite sure here. Maybe we should go a different direction here all together and use the same techniques ember uses in ember-router-generator. (Basically use [recast](https://github.com/benjamn/recast)) - Will investigate.

Working on it in #155

**Comment by pichfl** [comment]
Turns out that we can replace the whole environment.js shenanigans can be replaced by #156

**Comment by anulman** [comment]
Nice. Closing this issue to better track in #155 & #156
