### ISSUE TITLE
Packaging windows - UAC

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#158]
Hello!

After electron-packager, before use electron-builder, I have to embed into the executable a xml to ask for administrator privileges in windows (UAC)?

Like in this example: http://layer0.authentise.com/electron-and-uac-on-windows.html

There exists any way to call mt.exe command with ember electron or to embed the manifest with ember electron?

Thanks.

**Comment by anulman** [comment]
This is a great question @debelop13—took a quick review of the linked page, and it looks like this is doable.

If we need to use mt to generate the manifest, I think we'll defer this work to the 2.1 release (unless you'd like to issue a PR 😄). If, however, you find a way to pre-generate the manifest, have you tried using the `copy-files` option in package.json to copy it into the executable?

**Comment by malept** [comment]
It would be really cool if UAC/`mt.exe` support was its own Node module so that it can be used in Electron Forge (and thus in ember-electron) or if someone wanted to use Electron Packager and friends separately.

**Comment by malept** [comment]
This is being discussed in https://github.com/electron-userland/electron-packager/pull/610 (and related rcedit PRs).

**Comment by malept** [comment]
This feature has been released in Electron Packager 8.7.0, so you should be able to get it when you update your ember-electron dependencies.

**Comment by debelop13** [comment]
I updated dependencies and is not working yet.

    win32metadata: {
      CompanyName: 'S.L..',
      FileDescription: 'Installer',
      ProductName: 'Installer',
      InternalName: 'Installer',
      'requested-execution-level': 'requireAdministrator'
     },

Should I suppose that ember-electron must updated?

**Comment by malept** [comment]
Ah, if you're using Yarn, you'll need to wait for #248 to be merged/released.

**Comment by debelop13** [comment]
It works! Thanks!
