### ISSUE TITLE
Packaging windows - Sign 

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#159]
Hello!
 
I am packaging with ember electron and I want to sign my .exe without command line in windows.

Exists any way to sign a .exe with ember electron? It will be possible with 2.0?

Thanks!

**Comment by anulman** [comment]
Hi @debelop13—this should be possible today with the 2.0 work. Can you check #147 for 2.0 setup instructions? You'd use the `ember electron:make` command to generate the distributable, and [forge's `electronWinstallerConfig` options](https://github.com/electron-userland/electron-forge#possible-make-targets) to provide signing parameters.

**Comment by debelop13** [comment]
Hi!

This works with .exe created with ember:electron make.

But I want to sign .exe created with ember electron:package, with electron-packager. I should open issue in electron-packager?
