### ISSUE TITLE
'requireNode' is not defined

### ISSUE THREAD

**Issue by nahtnam** [felixrieseberg/ember-electron#164]
After creating a new app, if you try to import a node library, you get the following error: `'requireNode' is not defined`

The current workaround is to go to `node_modules/ember-electron/lib/resources` and edit both of the files and change `(this)` at the bottom to `(window)`. While the workaround works, it will fail in CI's and other places where you cant easily modify the `node_modules`.

Thanks.

**Comment by bendemboski** [comment]
Fixed in 2.0 via https://github.com/felixrieseberg/ember-electron/commit/118a140963685dc42faf97b54f7279807522b702
