### ISSUE TITLE
Packaging mac - Sign

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#166]
Hello!

I am trying to sign mac application, but it isn't signing correctly, but is not showing any warning or error showing the reason.

"osx-sign": {
      "identity": "Developer ID Application: Common name (UserID)",
      "entitlements": null,
      "entitlements-inherit": null
    },

I need help! Thanks

**Comment by jacobq** [comment]
Although I don't have a Mac readily available for my use, I think you may be missing some of the required information for packaging a signed mac application. Which target are you using? (dmg?)

The latest `ember-electron` uses [`electron-forge`](https://github.com/electron-userland/electron-forge), which uses [`electron-packager`](https://github.com/electron-userland/electron-packager),which uses [`electron-osx-sign`](https://github.com/electron-userland/electron-osx-sign), which I suspect is the module that is causing the problem.

**Comment by debelop13** [comment]
I am using dmg, yes.

I am not using electron-forge yet, I will  update to ember-electron 2.0

**Comment by debelop13** [comment]
Solved! It was a problem with my certificate.

Now I have .app correctly signed.

Anyway, I think that it should show errors or warning when you are trying to signing and it is not doing correctly.

**Comment by jacobq** [comment]
Would you be willing to check if there are errors generated by the upstream dependencies (e.g. electron-packager or electron-osx-sign)? If they are then we should make sure we don't suppress them here. If they're not then the changes should probably be made on those projects first.
