### ISSUE TITLE
Introduction to `ember-electron` at Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [felixrieseberg/ember-electron#17]
Would you someone familiar with the project would be open to giving an "Introduction to ember-electron" lightning talk at an upcoming Global Ember Meetup in the beginning of next year? We'll edit the video and give you video that you can embed into the addon's README. You can see an example of other introduction videos here https://vimeo.com/album/3607049

The talk usually covers:
1. What's use case for the addon?
2. How to get stated using it?
3. What should the user be aware of?

An "Introduction to" talk is about 15-20 min. We still have availabilities for Feb 27th or March 19th. 

Would you be interested in giving such a talk?

**Comment by felixrieseberg** [comment]
Sure, sounds like fun! How about Feb 27th?

**Comment by taras** [comment]
Awesome! You're booked :)

**Comment by felixrieseberg** [comment]
Fantastic :+1: I assume you'll ping me the days before for the tech setup, right?

**Comment by taras** [comment]
Yep!
