### ISSUE TITLE
Cannot force install platform specific NPM dependency

### ISSUE THREAD

**Issue by sfyfe31** [felixrieseberg/ember-electron#171]
I'm making a cross-platform Electron app. When run on Windows, I need to inspect the registry, so I'm using [regedit](https://github.com/ironSource/node-regedit).

I'm doing my development on macOS, so in order to install and use the dependency for development, I had to run `npm i -f regedit --save`, in order to force it to install on the unintended platform.

However, when I then come to package my app, I get:

```
Error installing a Node dependency into the Electron Build Directory:

Error: Unsupported platform for regedit@2.2.6
```

This seems to be as part of the [npmi](https://github.com/maxleiko/npmi) call:

`ember-electron/lib/commands/package.js:254`
```
npmi({name, version, path}, (err) => {
        if (err) {
          this.ui.writeLine('')
          this.ui.writeLine(chalk.red('Error installing a Node dependency into the Electron Build Directory:'))
          this.ui.writeLine('')
          this.ui.writeLine(chalk.yellow(err.toString()))
          return reject(err)
        }

        this.ui.writeLine('Installed and bundled ' + name + '@' + version)
        installedDeps.push(name)

        resolve(installedDeps)
      })
```

npmi has a `npmLoad["force"]` option, which I assume is the equivalent of `npm i -f package-name`.

Can this `npmLoad` option be somehow exposed in the app's `package.json:ember-electron` object?

**Comment by jacobq** [comment]
There's some work in progress for allowing platform-specific things to be packaged nicely in #123 
which may help with this, though I hadn't thought about it in the case of node_modules.

**Comment by anulman** [comment]
@sfyfe31 would calling to `npmi` with `npmLoad.force = true` on all `packageJson.optionalDependencies` work for your needs?

**Comment by sfyfe31** [comment]
It would've worked for this specific scenario, although that's using a cannon to kill a mosquito. Platform-specific dependencies/packaging - as jacobq alluded to - would probably be a more graceful solution

**Comment by anulman** [comment]
@sfyfe31 In that case, it will be difficult to land this in 2.0 without additional support. Is this feature a blocker from upgrading? If so, let's maybe consider using the sledgehammer for now (or I'd be happy to coach you through the contrib 😄)

**Comment by sfyfe31** [comment]
No, I ended up finding [winreg](https://github.com/fresc81/node-winreg), which doesn't need to be force installed on macOS/Linux. So problem solved for now. If I come across another Windows requirement where the NPM module is similar, then I'll have a look at submitting a pull request.

**Comment by bendemboski** [comment]
I'm going to close this, as it sounds like we're not going to act on it unless we find another failure case that somebody cares about.
