### ISSUE TITLE
Uncaught Error: Cannot find module 'devtron'

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#175]
When running the packaged app and opening the dev tools (made available via code), it can't seem to find the devtron module.

It should be fixed by adding devtron as a dependency, but maybe we should make our installation of devtron a bit more stable, only installing if the dependency was found and is included?

**Comment by jacobq** [comment]
I see this in the case of `ember electron` but not `ember electron:package`. Is that the same as your experience? Running `npm install --save devtron` does not seem to help.

**Comment by jacobq** [comment]
Also, it seems that even though the error message appears in the case of `ember electron`, the Devtron 'tab' is there whereas in packaged builds there is neither an error nor the corresponding tab. Furthermore, attempting to run `require('devtron')` in a packaged version causes the error to appear again. Seems related to `resources/electron.asar/common/reset-search-paths.js`

**Comment by pichfl** [comment]
Nope, happens to me in `ember electron:package` as well. Or well, scratch that, I had not installed devtron as a dependency at all. Strangely enough, devtron seems to be missing only when running in `--env=development` (which is the case for `ember electron` but not for `ember electron:package` by default. Adding the flag manually shows the error in both builds.

**Comment by jacobq** [comment]
Hacky but appears to work:
```
const fs = window.requireNode('fs');
const path = window.requireNode('path');
const module = window.requireNode('module');

// Check if we're running with resource root inside of a `electron-prebuilt-compile` dir.
// This should correspond to when running `ember electron`
const epcIndex = __dirname.indexOf('electron-prebuilt-compile');
if (epcIndex !== -1) {
  //let epcNodeModulesPath = path.resolve(__dirname.slice(0, epcIndex), '..', 'node_modules');
  const epcNodeModulesPath = __dirname.slice(0, epcIndex);
  if (fs.statSync(epcNodeModulesPath).isDirectory()) {
    module.Module.globalPaths.push(epcNodeModulesPath);
  }
}

// When running a packaged app, we have our modules in
// resources/app/node_modules
const eeNodeModulesPath = path.resolve(process.resourcesPath, 'app', 'node_modules');
if (fs.statSync(eeNodeModulesPath).isDirectory())
  module.Module.globalPaths.push(eeNodeModulesPath);
```

I think this is partly an upstream problem with `electron-prebuilt-compile`

**Comment by bendemboski** [comment]
I believe the root of the problem is [this](https://github.com/electron/electron/blob/5200b1a1ab6f76f5944c6d5f728bc51827101b31/lib/renderer/init.js#L106) code. When we load `index.html` via a `serve:` URL using `electron-protocol-serve`, `init.js` doesn't know at what path to situate the main module of the renderer process, and `require`s don't look in the right place.

**Comment by pichfl** [comment]
@bendemboski dang.
