### ISSUE TITLE
`electron-protocol-serve` should not be pinned to v1.1.0

### ISSUE THREAD

**Issue by jacobq** [felixrieseberg/ember-electron#192]
[Locking `electron-protocol-serve` to v1.1.0](https://github.com/felixrieseberg/ember-electron/blob/master/blueprints/ember-electron/index.js#L68) prevents users from getting improved/compatible new versions. I assume this was a mistake.

**Comment by bendemboski** [comment]
Oh yeah, typo. @anulman you want to just fix this in your branch since you're already all over that code?
