### ISSUE TITLE
[1.x] `ember electron:package` fails if `dependencies` is empty

### ISSUE THREAD

**Issue by jacobq** [felixrieseberg/ember-electron#196]
This may be related to `electron-rebuild`, but I thought it'd be worth filing a bug for this here since it appears that `ember electron:package` fails on a new/empty project created by `ember new ...` and `ember install ember-electron` (v1.12.7) even thought `ember electron` works.

```
...
Recompiling native dependencies
  electron-rebuild rebuilding with args: [ '/path/to/app/tmp/electron-build-tmp/',
  '1.6.2',
  'x64' ] +134ms
  electron-rebuild rebuilding with args: /path/to/app/tmp/electron-build-tmp/ 1.6.2 x64 [] false https://atom.io/download/electron [ 'prod', 'optional' ] +2ms
  electron-rebuild identified prod deps: {} +3ms
  electron-rebuild scanning: /path/to/app/tmp/electron-build-tmp/node_modules +1ms

Native compilation did not work:
Error: ENOENT: no such file or directory, scandir '/path/to/app/tmp/electron-build-tmp/node_modules'
```

**Comment by jacobq** [comment]
A simple work-around is to add something to `package.json` dependencies, e.g. `npm install --save underscore`

**Comment by pichfl** [comment]
See discussion in #131

**Comment by jacobq** [comment]
Ah, thanks; I didn't see that discussion. (Believe it or not, I did search first :D)
