### ISSUE TITLE
require('electron') - issues?

### ISSUE THREAD

**Issue by toovy** [felixrieseberg/ember-electron#20]
Hi felix,

I played around with this project and really appreciate it. Nevertheless I tried to open a dialog to let the user pick a file. Looking at the electron API this should be pretty straightforward. 

https://github.com/atom/electron/blob/master/docs/api/dialog.md

When I call require('electron') there is no dialog property. What am I doing wrong?

Thanks a lot, BR, toovy

**Comment by felixrieseberg** [comment]
This is probably easy - if you're trying to call `dialog` from anywhere in Ember, you're no longer in the main process. Simple example:

```
import Ember from 'ember';

export default Ember.Controller.extend({
    init: function () {
        var dialog = require('electron').remote.dialog;
        dialog.showErrorBox('Error', 'Hi!');
    }
});
```

I'm closing this in the meantime, but feel free to reopen if I misunderstood the situation :rabbit:

**Comment by toovy** [comment]
Works fine, thanks!
    
    dialog = require('electron').remote.dialog
    dir = dialog.showOpenDialog properties: [ 'openDirectory' ]

**Comment by BennyAlex** [comment]
@toovy  @felixrieseberg 
when I am using `const {dialog} = require('electron').remote;` I get the following error:

File: electron-mp3-wizard/controllers/renamer.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: electron-mp3-wizard]: Babel: electron-mp3-wizard] failed with:

> TypeError: my-app/controllers/renamer.js: Property object of MemberExpression expected node to be of a type ["Expression"] but instead got null

**Comment by seansellek** [comment]
I am also seeing the issue BennyAlex mentioned
