### ISSUE TITLE
Monaco-editor not working

### ISSUE THREAD

**Issue by smorzhov** [felixrieseberg/ember-electron#200]
Can you write a sample how to use monaco editor and ember-electron?
I've tried these examples:
- [sample-editor](https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-editor/index.html)
- [sample-electron](https://github.com/Microsoft/monaco-editor-samples/blob/master/sample-electron/index.html)

But they are not working due to `require.config` (1st example) and `amdRequire.config` (2nd example) is undefined. What am I doing wrong?

**Comment by felixrieseberg** [comment]
You're in luck, I wrote a thing: 

https://github.com/felixrieseberg/monaco-loader
https://github.com/felixrieseberg/electron-code-editor
