### ISSUE TITLE
Beta: Failed to locate startable Electron application

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#202]
@anulman and I are closing in on this as I'm writing this, so this is mostly for documentation.

Anyway, in the current master, `ember electron` wont start an application. While we copy and mangle the `package.json`, we can't copy over the `node_modules` folder as well, therefore the app in the tmp folder never has packages installed (we can't symlink them on windows and running npm install every time is madness).

So what I propose is to keep the forge config in it's short form in the main `package.json` so we can go a different route. This has the additional benefit that a user familiar with `electron-forge` will feel at home and we would be closer to our addon description, being a lightweight adapter to forge.

This will most likely change things we brought in with #188.

**Comment by pichfl** [comment]
Short update: Thanks to investigation by @anulman this can be resolved with a minimal change upstream, so we're working on the right way to resolve this now.

**Comment by kevingelion** [comment]
> keep the forge config in it's short form in the main package.json

Can you clarify what you mean? Will it still be an exported object or are you saying to just put the JSON inside `package.json`? Also after your comment I'm not sure my question is even relevant anymore.

**Comment by pichfl** [comment]
I should probably close this issue straight away, it was mostly me trying to wrap my head around everything.
