### ISSUE TITLE
Gif Image not showing on linux package

### ISSUE THREAD

**Issue by talhaobject90** [felixrieseberg/ember-electron#22]
Here the details of my environment:

ubuntu 12.04 (64-bit)
Node version v4.2.4
ember 2.2.2
"ember-electron": "0.3.4",

I created a package for linux, but my gif image for loading page is not showing on the app. it only displays the text. Is this default?

**Comment by felixrieseberg** [comment]
This is probably an upstream issue in atom/electron, so I'm closing this for now.
