### ISSUE TITLE
Huge app

### ISSUE THREAD

**Issue by villander** [felixrieseberg/ember-electron#221]
Hi, how i put a huge app splitted in several Ember.js applications into `ember-electron` ?

**Comment by pichfl** [comment]
While this is a question more suited for Slack, there are a few options here.

- use ember-electron only your main Ember application and pull in the other apps via broccoli. This way you can generate multiple entry files (index.html). You have to adapt the code in the electron main js file and either create a custom protocol for each entry or change the protocol completely to serve multiple entries. This may work.
- do not use ember-electron at all. While this might not be what you came for, ember-electron does not provide tooling for your situation. Use electron-forge directly. 
- refactor your application using ember engines, if appropriate. 

I wish I could be more helpful here, but I have no idea what the use case for such a scenario would be, which makes it really hard to give better suggestions.
