### ISSUE TITLE
Upgrade initializes git needlessly

### ISSUE THREAD

**Issue by xn** [felixrieseberg/ember-electron#226]
Well, I just crapped my pants for a moment:

```
[(ruby-2.3.1)] ~/sites/thinger/client <glimmer-2> ✗ ember generate ember-electron
installing ember-electron
  create ember-electron/.compilerc
  create ember-electron/.eslintrc.js
  create ember-electron/main.js
  create testem-electron.js
  create tests/ember-electron/.eslintrc.js
  create tests/ember-electron/main.js
Project needs forge config
NPM: Installed devtron@^1.4.0
NPM: Installed electron-protocol-serve@^1.3.0
Installed electron build tools
Created ember-electron resource dirs
Extracted ember-electron forge config
[(ruby-2.3.1)] ~/sites/thinger/client <master> ✗
```

So, the root git directory for this project is one directory up. Something in the upgrade process didn't detect that and decided to init git. Removed `.git` directory and back to normal.

**Comment by felixrieseberg** [comment]
Oh wow, that's _not good_. I'll bring that up with electron-forge. Thanks for the report!

**Comment by bendemboski** [comment]
`electron-forge` isn't set up to operate out of not-the-root of the git repo. You could probably propose an option to disable git initialization that we could then set in our blueprint, or try to get them to recursively walk up the directory tree looking for `.git` directories to automatically fix this issue. But either way, we can't really do anything about it without something happening in `electron-forge` so I'm going to close this issue.
