### ISSUE TITLE
Ghost Example Upgrade unavailable

### ISSUE THREAD

**Issue by benoror** [felixrieseberg/ember-electron#230]
Link to https://github.com/felixrieseberg/ember-electron/blob/master/docs/guides/ghost-pr in [upgrade.md#example-upgrade](https://github.com/felixrieseberg/ember-electron/blob/master/docs/guides/upgrade.md#example-upgrade) is not available, could we get it back?

**Comment by pichfl** [comment]
We had a small markdown error in our docs, which I fixed in e56d0f7.

See https://github.com/TryGhost/Ghost-Desktop/commit/6fce208c7c3ba18c385de4123095be81bd0e614d or the current [Master branch](https://github.com/TryGhost/Ghost-Desktop) of Ghost for the example.
