### ISSUE TITLE
Installation fails with Yarn present

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#231]
While I know that this is issue right now, we should probably document this a bit more. I'll extend on this issue with all existing problems soon.

TLDR;
`ember install ember-electron` does not work as expected after `yarn` was run in the repo because how we execute the tasks for the additional dependencies right now. A fix should be rather easy for someone familiar with the ember-cli task system.

**Comment by bendemboski** [comment]
The latest yarn release (0.23.2) contains the optional dependencies fix that was causing a non-MacOS install to barf on `appdmg`.

**Comment by pichfl** [comment]
I made this issue because

```sh
ember init
ember install ember-electron
```

failed on me a few hours ago, will have to investigate why.

**Comment by pichfl** [comment]
Jupp still fails. Error due to `yarn install` which should be `yarn add`
 
```sh
❯ ember install ember-electron
Yarn: Installed ember-electron
installing ember-electron
  create ember-electron/.compilerc
  create ember-electron/.eslintrc.js
  create ember-electron/main.js
  create testem-electron.js
  create tests/ember-electron/.eslintrc.js
  create tests/ember-electron/main.js
Project needs forge config
Command failed: yarn install devtron@^1.4.0
error `install` has been replaced with `add` to add new dependencies. Run "yarn add devtron@^1.4.0" instead.
yarn install v0.23.2
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error: Command failed: yarn install devtron@^1.4.0
error `install` has been replaced with `add` to add new dependencies. Run "yarn add devtron@^1.4.0" instead.
yarn install v0.23.2
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (/Users/pichfl/Desktop/eedemo/node_modules/execa/index.js:210:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by pichfl** [comment]
Further investigation shows:
https://github.com/felixrieseberg/ember-electron/blob/master/blueprints/ember-electron/index.js#L63

Does not set the `useYarn` option which results in unexpected behaviour here: https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/npm-task.js

I think @anulman worked on that while the big refactoring for 2.0.

**Comment by pichfl** [comment]
Turn out this is not fixed yet. 

I made a PR with ember-cli to fix the wrongful invocation of yarn here: ember-cli/ember-cli/pull/6965

Upcoming: A PR correcting `saveDev` to `save-dev` in our NPM task invocations. Thanks to @gokatz in Slack for the investigation.
