### ISSUE TITLE
Better handling for main entry in package.json

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#232]
Extracted from #216 

@bendemboski 

> @anulman @pichfl your thoughts here? We could just make a note in the upgrade guide/faq, or we 
> could look into modifying the blueprint to delete `main` out of `package.json`? Or perhaps only 
> target the v1->v2 upgrade case, and only delete it if it points to `electron.js`?
> 
> Either way, I think it makes sense to ensure that the `main` entry points to a file that exists when 
> running `ember electron` (probably any `ember electron😚` command), and if not bail with a more 
> descriptive error than the super-cryptic one that these folks had to deal with (sorry, friends!). Or 
> perhaps this `main` verification belongs upstream in `electron-forge` -- @anulman your thoughts?

**Comment by anulman** [comment]
See https://github.com/felixrieseberg/ember-electron/issues/147#issue-210593221
