### ISSUE TITLE
Tests fails on initial app

### ISSUE THREAD

**Issue by hugoruscitti** [felixrieseberg/ember-electron#238]
Hello!, I have an initial app to try ember-electron but it seem to be
somethink wrong. When i run `ember electron:tests` i get:

![12 2017-04-20 19-00-34](https://cloud.githubusercontent.com/assets/99183/25254392/bcfb03da-25fb-11e7-9beb-53e98de08b05.png)

This file called `ember-electron/main.js` is an internal file of this addon right? or i make some
mistake installing the addon?

**Comment by bendemboski** [comment]
Hi, thanks for the bug report! This is a bug in `ember-electron`  and not your fault. I'm working on fixing it as we speak. To fix it in your application, just add `/* eslint-env node */` to the top of your `ember-electron/main.js`.

**Comment by hugoruscitti** [comment]
Oh, thanks!!!
