### ISSUE TITLE
Investigate: require shim no longer working in 2.x

### ISSUE THREAD

**Issue by pichfl** [felixrieseberg/ember-electron#241]
Seems there is some problem with the way we handle `require`. See https://github.com/felixrieseberg/ember-electron/issues/147#issuecomment-297407509 

This used to work and as I refactored there, I might have made an error. Will investigate.

**Comment by bendemboski** [comment]
I don't think there's a bug -- the comment was updated to indicate that it was a `require` vs. `requireNode` problem.

At some point it might be worth looking to getting rid of that by using `loader.js`'s [noConflict](https://github.com/ember-cli/loader.js#no-conflict) functionality...
