### ISSUE TITLE
Documentation not clear about unpackDir - How to use it?

### ISSUE THREAD

**Issue by danidr** [felixrieseberg/ember-electron#242]
Hello,
I am in the need of keeping some files unpackaged from the app.asar file, therefore I am trying to use the documented asar.unpackDir option.
Specifically, the relevant lines are:
```
"electronPackagerConfig": {
	  "name": "Configurator",
	  "icon": "ember-electron/resources/icons/configurator",
		"asar": true,
		"asar.unpackDir": "configurator/**/*",
		"appCopyright": "©2017 All Rights Reserved.",
		"electronVersion": "1.4.13",
		"buildVersion": "0.2.0"
  },
```

Of course, the directory I want to keep unpackaged is `./ember-electron/resources/configurator`, and all its contents.
When I package the application, though, this folder is completely ignored, neither added to the app.asar, or to the resources directory.
I believe I am doing something wrong, but there is no documentation giving any clear example...
Anyone could point me to the right direction?
Thank you.

**Comment by bendemboski** [comment]
@danidr sorry this has sat for so long! I imagine you've figured it out or worked around it by now, but I believe what you want is

```
"asar": {
  "unpackDir": "configurator/**/*"
}
```

**Comment by bendemboski** [comment]
More generally, we should fix [this](https://github.com/felixrieseberg/ember-electron/blob/master/docs/guides/configuration.md) guide, as it says that the options can be passed on the command-line (which isn't true), and documents them in command-line form rather than config JSON form.

**Comment by anulman** [comment]
@bendemboski closing this issue to focus on the Update Documentation (#328) issue

**Comment by e-sauvage** [comment]
> @danidr sorry this has sat for so long! I imagine you've figured it out or worked around it by now, but I believe what you want is
> 
> ```
> "asar": {
>   "unpackDir": "configurator/**/*"
> }
> ```

But what i do if i want to exclude or unpack more than one dir? 
If i do : `"asar": {
  "unpackDir": "{files/**/*, files/*}"
},`

it works but when i add for example this:
`"asar": {
  "unpackDir": "{files/**/*, files/*, node_modules/phantomjs/*, node_modules/phantomjs/**}"
},`

He does not unpack the node_module. Is there any Documentation about this?
