### ISSUE TITLE
The "out" option does not works

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#244]
Hello! 

Is working If I do this: ember electron:package --platform=darwin --out=electron-out/pack

But using electron-forge, not: 

'electronPackagerConfig': {
    appCategoryType: 'public.app-category.productivity',
    name: 'Install',
    platform: [
      "darwin",
      "win32"
    ],
    arch: "x64",
    asar: false,
    out: "electron-out/pack",
    overwirte: true,
    overwrite: true,
    icon: 'public/assets/build/packed'
  },

I am not sure that it is an ember-electron or electron-forge error...

**Comment by bendemboski** [comment]
Yeah, I think this is going to be a tough one -- looks like it's being overwritten by both `electron-forge` and `ember-electron`. `ember-electron`'s `electron:package` command has a default value for the output directory which it passes into `electron-forge` (so `electron-forge` doesn't know that it's a default value, it just sees a value). Then `electron-forge` passes a default value into `electron-packager`, so even if `ember-electron` didn't supply a value, `electron-forge` would. So poor `electron-packager` has no clue if the value it's given is a default value, and if it should be using what's in the config.

This is probably fixable, but would be a little be tricky. I'd recommend you find a way to work around it.

**Comment by bendemboski** [comment]
Closing -- please reopen if this is still causing you problems.
