### ISSUE TITLE
"electronVersion: '1.3.15'" is not working

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#254]
Hi! 

I want to use the last release of electron (1.3.15), and is compiling with last version (1.6.6) anyway.

electronPackagerConfig: {
    appCopyright: 'Copyright (c) 2017',
    arch: 'x64',
    asar: false,
    derefSymlinks: false,
    electronVersion: '1.3.15',
    name: 'Install',
    out: 'electron-out',
    overwrite: true,
    platform: [
      'darwin',
      'win32'
    ],
    appCategoryType: 'public.app-category.productivity',
    osxSign: true,
    win32metadata: {
      CompanyName: 'S.L.',
      FileDescription: 'Installer',
      ProductName: 'Installer',
      InternalName: 'Installer',
      'requested-execution-level': 'requireAdministrator'
     },
  },

Thanks!

**Comment by bendemboski** [comment]
This appears to be working now (with the last few `electron` versions). Please re-open if it's still causing you trouble.
