### ISSUE TITLE
Ember 2.13 Targets Feature question

### ISSUE THREAD

**Issue by xn** [felixrieseberg/ember-electron#258]
reference:

[Targets RFC](https://github.com/ember-cli/rfcs/blob/master/complete/0095-standardise-targets.md)

Does this impact ember-electron projects in any way?

Out of the box we are given this configuration:

```
module.exports = {
  browsers: [
    'ie 9',
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```

Are there better or more appropriate values to have here?

Thanks.

**Comment by bendemboski** [comment]
Haven't started playing with targets yet, but it uses [browserlist](https://github.com/ai/browserslist) which has an `electron` target, so if you're only building an electron app (not also a web app), you could probably just use that target. Although you'd have to investigate how to specify which electron version you care about.

**Comment by hinti** [comment]
Unfortunately the target feature doesn't work with ember-electron **2.2.2**.

Environment:
```
ember-cli: 2.13.2
node: 6.11.0
os: darwin x64
```

Create new project and install ember-electron

```
ember new foo
ember install ember-electron
```

**Remove IE9** from _targets.js_

```
module.exports = {
  browsers: [
    'last 1 Chrome versions',
    'last 1 Firefox versions',
    'last 1 Safari versions'
  ]
};
```
Start ```ember s``` and open ```http://localhost:4200/tests```

Error: ```tests.js:27 Uncaught SyntaxError: Missing initializer in destructuring declaration```
File: ```foo/tests/ember-electron/main' ```
