### ISSUE TITLE
Integrate Ember Inspector

### ISSUE THREAD

**Issue by locks** [felixrieseberg/ember-electron#26]
From what I understand it should be possible to integrate Ember Inspector with this addon, to make it possible to debug the application more easily.

Related: https://github.com/atom/electron/blob/master/docs/tutorial/devtools-extension.md https://github.com/emberjs/ember-inspector/issues/511

**Comment by felixrieseberg** [comment]
Bad news: We don't run a server for Electron, so Ember Inspector Remote won't work - and the Ember Inspector Extension does *not* work in Electron (believe me, I tried). We have similar issues with the React Explorer.

This is therefore blocked (https://github.com/atom/electron/issues/915).

**Comment by locks** [comment]
:pipedream: :hammer:

**Comment by felixrieseberg** [comment]
I know I *just* said two days ago that I wouldn't be able to support it - but as it turns out, I was able to integrate with the ember-inspector's websocket implementation. Pull down :sparkles: 0.5.0 :sparkles and you'll get a working Ember Inspector ;-)

**Comment by locks** [comment]
:tada: :tada: :tada: updating Ember Hearth right meow :D
