### ISSUE TITLE
Keyboard built-in events not received by component

### ISSUE THREAD

**Issue by simpleshadow** [felixrieseberg/ember-electron#260]
Hi All,

Just started using ember-electron and I've got components will not receive any of the `keyUp`, `keyDown`, or `keyPress` [built-in keyboard events](https://guides.emberjs.com/v2.13.0/components/handling-events/#toc_event-names), though receives the `click` no problem.

What am I missing? I tried a few workarounds without success and would much rather just use it as designed. :)

**Comment by simpleshadow** [comment]
My mistake. Closing. I need to bind the event to the `document` as the component is not focused to receive that event. 👍

**Comment by pichfl** [comment]
Depending on what you want to achieve you could also use the Electron API and register shortcuts there by either creating menu items which specify accelerators or by creating global shortcuts. https://github.com/electron/electron/blob/master/docs/api/accelerator.md
