### ISSUE TITLE
Building with ember-cli fingerprinting enabled

### ISSUE THREAD

**Issue by timmyomahony** [felixrieseberg/ember-electron#261]
I'm trying to compile an existing web app as an Electron app. The web app is being deployed to S3 and is using fingerprinting so I have the following in my `ember-cli-build.js`:

```
switch (env) {
    case 'development':
      fingerprintOptions.prepend = 'http://localhost:4200/';
    break;
    case 'production':
      fingerprintOptions.prepend = 'https://myapp.s3.amazonaws.com/';
    break;
  }

  var app = new EmberApp(defaults, {
    sassOptions: {
      includePaths: [
        'bower_components'
      ]
    },
    fingerprint: fingerprintOptions
  });
```

When I try to run the app with `ember electron` the fingerprinting is causing all of my assets to be loaded as:

    http://localhost:4200/assets/vendor-04b71f4abbf81d1fdde5898deb6656e1.css 

as opposed to:

   file://assets/vendor.css

Are there any flags I can use in the configuration to disable fingerprinting when building for Electron? Or is there an existing approach for this?

**Comment by timmyomahony** [comment]
Ok, so one easy solution is to have multiple `environment` variables:

- `web_production`
- `web_development`
- `desktop_production`
- `desktop_development`

and disable fingerprinting with something like:

```
if (env.indexOf('web') != -1) {
    fingerprintOptions = {
      enabled: true,
      extensions: ['js', 'css', 'png', 'jpg', 'gif', 'map', 'svg', 'eot', 'woff', 'woff2', 'ttf']
    };

    switch (env) {
    case 'web_development':
      fingerprintOptions.prepend = 'http://localhost:4200/';
      break;
    case 'web_production':
      fingerprintOptions.prepend = 'https://myapp.s3.amazonaws.com/';
      break;
    }
  }

  var app = new EmberApp(defaults, {
    sassOptions: {
      includePaths: [
        'bower_components'
      ]
    },
    fingerprint: fingerprintOptions
  });
```

Then build with `ember electron --environment=desktop_development`.

I've noticed a few discussions on how to handle platforms in general:

- https://github.com/ember-cli/rfcs/issues/26
- https://github.com/ember-cli/rfcs/pull/35/files

so I'd be interested to hear how people approach this.

**Comment by bendemboski** [comment]
I have an app that runs both in Electron and on the web. I'm only interested in fingerprinting in production, not in development, so I just do:

```
fingerprint: {
  prepend: process.env.EMBER_CLI_ELECTRON ? '' : 'https://tp-eureka.s3.amazonaws.com/'
}
```
