### ISSUE TITLE
ember electron:package result missing module available when running plain old ember electron

### ISSUE THREAD

**Issue by tangollama** [felixrieseberg/ember-electron#262]
I'm looking to complete the electron build of the [HospitalRun 1.0 beta](https://github.com/HospitalRun/hospitalrun-frontend) and I can't seem to get past this issue. I *think* it's a bug.

# Behavior
`> ember electron`
App opens as normal.
<img width="1280" alt="screen shot 2017-05-22 at 8 33 04 am" src="https://cloud.githubusercontent.com/assets/929261/26308955/4f79a924-3ec9-11e7-89dd-dabd1e05d999.png">
However when I run,
`> ember electron:package`
a binary is produced that, upon open offers the following error:
![screen shot 2017-05-19 at 1 39 54 pm](https://cloud.githubusercontent.com/assets/929261/26309038/7a2f2d24-3ec9-11e7-9f28-fac7b12310ba.png)
The library referenced is in the [ember-electron/main.js](https://github.com/HospitalRun/hospitalrun-frontend/blob/master/ember-electron/main.js), line 3.

I'd be happy to hear that I'm an idiot and/or missed some change in the move from 1 to 2, but all I can tell so far is that it used to work (i.e. I had it building on ember-electron 2.0.1) and now it doesn't.

## Version
`ember-electron 2.1.0`

**Comment by bendemboski** [comment]
Could it be that `electron-protocol-serve` is in your `devDependencies`
rather than your `dependencies`?

**Comment by tangollama** [comment]
The dependency was actually in both. I removed it from devDependencies, and now we're working. Thanks @bendemboski. Closing the issue.
