### ISSUE TITLE
disable livereload

### ISSUE THREAD

**Issue by Dimebag03** [felixrieseberg/ember-electron#263]
I can't find the option to disable the livereload and the livereload still on when i package electron.

thank you :smile:

**Comment by pichfl** [comment]
Please document what exactly you're doing. 
Please post the versions of ember-cli and ember-electron you're using. 

Did you package using `--env=Production`? Otherwise there is a chance you packaged your development build which would include the live reload.

**Comment by Dimebag03** [comment]
Sorry for don't post the version and don't post the version of the ember-cli and ember-electron :disappointed: 

And the `--env=Production` worked for me, thx
Where i find more documentation about this?

Thank you :smiley:

**Comment by pichfl** [comment]
This is a feature of Ember CLI: https://ember-cli.com
Our documentation can be found in our README: https://github.com/felixrieseberg/ember-electron#documentation
