### ISSUE TITLE
Reload fails with dev tools open.

### ISSUE THREAD

**Issue by bartam** [felixrieseberg/ember-electron#267]
Running on windows, live reload fails if I have dev tools open.  

In the `ember electron` output, the build looks like it succeeds, but the electron app is blank.  I'm unsure  how to collect more debugging information.  

I reproduced it by:

1. `ember new dummy`
2. `cd dummy`
3. `ember install emeber-electron`
4. `ember electron`
5. Alter application template to verify reloading works with dev tools closed.
6. Open devtools
7. Alter application template -> broken

**Comment by bendemboski** [comment]
I believe this is fixed in the latest release -- please re-open if not
