### ISSUE TITLE
Not packaging all targets

### ISSUE THREAD

**Issue by sfyfe31** [felixrieseberg/ember-electron#270]
Just updating a project to ember-electron 2.1.0 and I'm finding that it's only packaging a macOS app, when I'm configuring it to create Windows and Linux to.

To update ember-electron, I updated my `package.json` dependency version number and:

```
npm i
ember g ember-electron
```

`ember-electron/electron-forge-config.js`

```
module.exports = {
  "make_targets": {
    "win32": ["squirrel"],
    "darwin": ["dmg"],
    "linux": ["deb"]
  },
  "electronPackagerConfig": {
    "asar": true,
    "icon": "icons/icon",
    "name": "vDrive",
    "overwrite": true
  },
  "electronWinstallerConfig": {},
  "electronInstallerDebian": {},
  "electronInstallerDMG": {}
}
```

`ember electron:package` output:

```
Packaging Electron project.
✔ Preparing to Package Application for arch: x64
⠇ Compiling ApplicationFailed to compile file: /var/folders/pw/bmm2l9ps6xg386g29_733j100000gp/T/electron-packager/darwin-x64/vDrive-darwin-x64/Electron.app/Contents/Resources/app/ember/crossdomain.xml
Compiling /var/folders/pw/bmm2l9ps6xg386g29_733j100000gp/T/electron-packager/darwin-x64/vDrive-darwin-x64/Electron.app/Contents/Resources/app/ember/crossdomain.xml resulted in a MIME type of application/xml, which we don't know how to handle
✔ Compiling Application
✔ Preparing native dependencies
✔ Packaging Application
```

But it's only creating a darwin application in the `electron-out` directory. No errors, just not attempting to create the Windows or Linux apps.

Is there something I'm missing? I know `electron-forge-config.js` is being used because changing the `electronPackagerConfig.name` property changes the name of the created macOS app.

**Comment by bendemboski** [comment]
The `make_targets` config only specifies what kinds of installers to build for each platform, it doesn't instruct the make or package command to actually build for those platforms. You need to run separate `ember electron:package` commands using the `--platform` argument to build for the cross-compiled platforms.

**Comment by sfyfe31** [comment]
Great. `ember electron:package --platform darwin,linux,win32` works.
