### ISSUE TITLE
can't "make" platform win32 on OSX

### ISSUE THREAD

**Issue by fredguth** [felixrieseberg/ember-electron#278]
ember electron:make --platform=win32

 Here is what happens:
> Making Electron project.
> An error occured while making for target: squirrel
> Failed with exit code: 255
> Output:
> System.AggregateException: One or more errors occurred. ---> System.Exception: err:process:create_process 64-bit application L"Z:\\Users\\fredguth\\Code\\remoto\\remoto-app\\node_modules\\electron-winstaller\\vendor\\7z.exe" not supported in 32-bit prefix
> wine: Bad EXE format for Z:\Users\fredguth\Code\remoto\remoto-app\node_modules\electron-winstaller\vendor\7z.exe.
>   at Squirrel.Utility+<CreateZipFromDirectory>d__23.MoveNext () [0x000ff] in <21211793586c42f8b401cfaec4ea8ad2>:0
>    --- End of inner exception stack trace ---

I do have mono and wine installed (via brew).
Tried:

> WINEARCH=win32 WINEPREFIX=~/.win32 winecfg

and

> WINEARCH=win64 WINEPREFIX=~/.wine64 winecfg

No difference.

**Comment by fredguth** [comment]
Relates to: https://github.com/electron/windows-installer/issues/186

**Comment by dknutsen** [comment]
I just ran into this, downgrading electron-winstaller to 2.5.2 (i just temporarily added it to my package.json) fixed it

**Comment by dknutsen** [comment]
Of course the generated installer is still broken...

**Comment by felixrieseberg** [comment]
I'm closing this issue as it seems like an upstream one - with little for us to do. Thanks!
