### ISSUE TITLE
Enter does not work in testing

### ISSUE THREAD

**Issue by yrtejas** [felixrieseberg/ember-electron#280]
Electron is unable to restart the test on hitting ENTER. I am using 'q' or Cmd + c  instead. 
Is there anything I should be doing to make the Enter work?

**Comment by yrtejas** [comment]
`ember electron:test -s`

**Comment by felixrieseberg** [comment]
This will likely never work, since we're barely keeping the connection between Electron and Ember Cli alive.

A PR would be super welcome, but I'm closing this as a "Sorry, no time, won't fix 😅". Thanks for reporting though!
