### ISSUE TITLE
[question] Does ember-electron publish?

### ISSUE THREAD

**Issue by fredguth** [felixrieseberg/ember-electron#281]
Ember-electron uses electron-forge which is capable of publishing files to github and s3.  Is it possible to use ember-electron to do it?

**Comment by bendemboski** [comment]
It does not right now, although I think @anulman said he might have time to look into it soon? Or if you are interested in contributing and want to take a stab at this, you can find me in Ember community slack and hit me up if you need some pointers.

There is a way to accomplish it using the [build pipeline](https://github.com/felixrieseberg/ember-electron/blob/master/docs/guides/build-pipeline.md) and `electron-forge`, but it's not a simple `ember-electron` command.

If you run `ember electron:assemble`, it will build your Ember app and assemble it along with your Electron resources into a fully-`electron-forge`-compatible project in `electron-out/project`. So I haven't tried this, but I think you should be able to do something like:

```
$ ember electron:assemble
$ cd electron-out/project
$ ./node_modules/electron-forge/dist/electron-forge.js publish
```

**Comment by anulman** [comment]
Thanks Ben! Yup, still in the cards; I expect to publish a PR mid-July :)

**Comment by fredguth** [comment]
Couldn't find electron-forge in electron-out/project/node_modules, though.
What I see:
electron-compile/           electron-protocol-serve/    electron-squirrel-startup/

I find it in ./node_modules (ember app node modules)....

**Comment by bendemboski** [comment]
Then try:

```
$ ember electron:assemble
$ ./node_modules/electron-forge/dist/electron-forge.js publish electron-out/project
```

**Comment by fredguth** [comment]
I works with Github but not for S3.
Can't figure out why.
my s3 config.
 ```
 "s3": {
    "accessKeyId": "AK ... OA",
    "secretAccessKey": process.env.AWS_SECRET_ACCESS_KEY,
    "bucket": "releases",
    "public": true
  }
```
I have tried with accessKeyId and also accessKey. And I do have set AWS_SECRET_ACCESS_KEY in my environment, and also ELECTRON_FORGE_S3_SECRET_ACCESS_KEY with the same value.

**Comment by bendemboski** [comment]
At this point I think you're looking at an issue with `electron-forge`, not `ember-electron`.

**Comment by fredguth** [comment]
sure.

**Comment by ibrahimab** [comment]
Are there any plans to make a ember electron:forge publish electron-out/project command?

**Comment by anulman** [comment]
Yes; this feature is a reasonably frequent request. My sincerest apologies for dropping the thread; we had closed the issue and I forgot to tie this loose end when July got hectic.

@ibrahimab can you open a new issue where we can track this, and maybe there describe more about your publishing flow?
