### ISSUE TITLE
"Serving on" not provided with ember electron

### ISSUE THREAD

**Issue by iamjstates** [felixrieseberg/ember-electron#282]
When I'm testing/local development my emberjs application I'm using ember serve which goes to localhost:99. With ember electron that does not work. It's probably a simple configuration but searching through these issues here yields nothing. How does this work, or should I be doing something else.

Thanks

**Comment by bendemboski** [comment]
When you're running your app using `ember electron`, it doesn't run an express server -- all assets are served out of the filesystem, so there is no server to connect to and no port to configure...what exactly are you trying to do?

**Comment by iamjstates** [comment]
That answers my question. It does not run a express server. I guess I'll have to change the way it runs. I configured my emberjs application to use express in testing. I just didn't want to total change my configuration to just run electron.
