### ISSUE TITLE
Ember electron menu interaction for testing

### ISSUE THREAD

**Issue by devinaction** [felixrieseberg/ember-electron#286]
Is there any way I can select the menu options of Electron in my Ember acceptance test? Please guide. I have followed https://github.com/electron/spectron/issues/21 but am looking for more resources.

**Comment by bendemboski** [comment]
No, there is currently no nicely boxed-up way to do this. If I were going to try to do something like this, I would probably try to implement a test-only IPC listener in the main process that can receive messages from the renderer processes and run code that simulates clicking on menu items.

`tests/ember-electron/main.js` is used in place of `ember-electron/main.js` when running `ember electron:test`, so you can put test-only main process code there. If you register an IPC listener for some kind of an event that you can send from your tests specifying the menu item you want clicked, then the main process code could call `Menu.getApplicationMenu()`, look up the menu item specified by the renderer process, make sure it's enabled or whatever other validation logic you want, and then invoke its click handler manually.

So you'd still have to do the work to implement the "click this menu item for me" protocol, and the logic to look up and validate the menu item and call its click handler.

I haven't actually implemented this myself, but that's the best way I can currently think of to achieve this inside Ember tests. There might be a better way to achieve what you want using `electron-mocha`, but there isn't a good way to run any Ember code under `electron-mocha` now, so you'd really just be testing the main process.
