### ISSUE TITLE
ember-inspector missing from 0.5.0

### ISSUE THREAD

**Issue by BryanHunt** [felixrieseberg/ember-electron#29]
I'm trying to get 0.5.0 working.  After I install 0.5.0, when I do an ember init, I get the following:

Error: ENOENT: no such file or directory, open '/[stuff deleted]/node_modules/ember-electron/node_modules/ember-inspector/dist/websocket/index.html'

**Comment by felixrieseberg** [comment]
Thanks for the quick report! I'm fairly certain this has something to do with npm, so I added a few functions that deal with differences - would you mind installing the patch (`npm install ember-electron@0.5.1`) and letting me know if that works?

**Comment by BryanHunt** [comment]
The above error is solved with 0.5.1, but now I get:

TypeError: root path must be a string

**Comment by felixrieseberg** [comment]
Hm, weird. What version of npm and Node are you using?

**Comment by BryanHunt** [comment]
Bryans-iMac:ember-ham-radio bhunt$ node -v
v5.5.0

Bryans-iMac:ember-ham-radio bhunt$ npm -v
3.3.12

**Comment by felixrieseberg** [comment]
Thanks! Installed the same versions, found the error, issue fixed - 0.5.2 ;-)

**Comment by BryanHunt** [comment]
0.5.2 has fixed this problem.

I do have another strange problem.  Would you have time to discuss on Slack?

**Comment by felixrieseberg** [comment]
Sure! Closing this for now :)
