### ISSUE TITLE
Electron-rebuild warning on startup

### ISSUE THREAD

**Issue by plck** [felixrieseberg/ember-electron#295]
When running `ember electron` I get the warning 'You are using the depreceated electron-rebuild API, please switch to using the options object instead'. Tried this with a new project.

ember-cli: 2.14.2
node: 6.9.1
os: darwin x6

**Comment by bendemboski** [comment]
This is an issue with [electron-forge](https://github.com/electron-userland/electron-forge/), not `ember-electron. Feel free to file an issue there, but I'm going to close this one out since there's nothing we can do about it here.
