### ISSUE TITLE
How to build a release package

### ISSUE THREAD

**Issue by jprberlin** [felixrieseberg/ember-electron#3]
Hi,

thanks for this package. I combined this with the menu package and it works great. But how can i build a release package?

Thanks, Jan

**Comment by felixrieseberg** [comment]
Hey, this package enables a dev/build/test workflow with Electron, but leaves everything else untouched. From Electron's point of view, it's still just a simple app.

We at Microsoft are using Grunt and the usual Electron Grunt packages to build and package - you can find our Gruntfile here, if you're curious: https://github.com/azure-storage/deco/blob/master/Gruntfile.js

I'll close this in the meantime, but feel free to shoot more questions :rocket:

**Comment by jprberlin** [comment]
Thanks. Using Grunt sounds fine.

**Comment by nicksmetBagaar** [comment]
@felixrieseberg I used a modified version of your grunt file to build my release packages. 

I've got a couple of questions : 
1) For osx, does it also build a dmg with an installer ? When building the package now only a .app is created. 
2) for windows the build fails on 'windowsWithIcon', with the error : 
```
Packaging app for platform win32 ia32 using electron v0.35.1
Warning: fixme:heap:HeapSetInformation 0x0 1 0x0 0
Fatal error: Unable to parse version string
Use --force to continue.
```

This is the grunt task itself : 
```
windowsWithIcon: {
   options: {
         name: 'STC',
         platform: 'win32',
         arch: 'all',
         dir: 'electronbuildcache',
         out: 'builds',
         version: '0.35.1',
         overwrite: true,
         icon: 'public/icon/ase.ico',
         asar: true,
         'version-string': {
            ProductName: 'STC',
            ProductVersion: getVersion(),
            FileDescription: 'STC',
            ProductVersion: 'stc.exe'
         }
    }
 },
```

I'm working on mac, wine is installed : version 1.6.2

**Comment by felixrieseberg** [comment]
It does not build a dmg - in the same repo, you can find python scripts that do that though. I assume you're running into Wine issues, I'd recommend using actual Windows. I'd report the issue over at https://github.com/maxogden/electron-packager, which I'm using in my Gruntfile.

**Comment by nicksmetBagaar** [comment]
ok, I'll try it on a windows and let you know it it worked.

Thanks !
