### ISSUE TITLE
Ember Inspector is not getting installed

### ISSUE THREAD

**Issue by locks** [felixrieseberg/ember-electron#30]
When trying to run `ember electron` on Ember Hearth, I am getting the following error:

```bash
ENOENT: no such file or directory, open '/Users/locks/src/ember-hearth-mun/node_modules/ember-electron/node_modules/ember-inspector/dist/websocket/index.html'
> Error: ENOENT: no such file or directory, open '/Users/locks/src/ember-hearth-mun/node_modules/ember-electron/node_modules/ember-inspector/dist/websocket/index.html'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.<anonymous> (/Users/locks/src/ember-hearth-mun/node_modules/ember-electron/lib/helpers/debug-server.js:24:24)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

I managed to temporarily fix the problem by going into `node_modules/ember-electron` and running `npm install`.

**Comment by felixrieseberg** [comment]
Thanks for letting me know - given that we can't really predict where npm will ultimately install dependencies, the next best thing we can do is to just add it to the root-level dependencies.

If you update with 0.5.3 (and run ember g ember-electron), everything should work fine. I'll close in the meantime, but I'd love if you could check if that fixes the issue for you!

**Comment by locks** [comment]
Could making it a peer dependency help? In npm3 they aren't installed by default anymore. Or is that what you did already? I'm not too familiar with the ways of the npms.

**Comment by locks** [comment]
For all intents and purposes it seems fixed, appreciated :)

**Comment by felixrieseberg** [comment]
Cool, thanks for checking!
