### ISSUE TITLE
Testing SVG Drag and drop 

### ISSUE THREAD

**Issue by devinaction** [felixrieseberg/ember-electron#301]
How can we test drag and drop features? 

I am writing an acceptance test to drag SVG elements around. Has anyone encountered anything similar to this? #helpwanted

**Comment by bendemboski** [comment]
@devinaction is your question somehow specific to electron or ember-electron? I think you'd do it the same way you'd do it in a browser, so this question would be better suited to Ember Community Slack.

**Comment by devinaction** [comment]
Thank you! I will head on to the Ember slack. Please close this.
