### ISSUE TITLE
Installing spectron on ember electron for testing

### ISSUE THREAD

**Issue by devinaction** [felixrieseberg/ember-electron#304]
Has anyone installed spectron for ember electron. I want to use the webdriverIO for the drag and drop

Update: Found an example which implements Spectron with Electron but the unable to figure out how to configure the path for the test. Any 2 cents will help regarding the `electronPath`.

Link: https://github.com/jwood803/ElectronSpectronDemo/blob/master/tests/test.js

Posted on SO https://stackoverflow.com/questions/45908530/path-configuration-for-testing-ember-electron-with-spectron too. 

I do not have an .exe or .cmd but how do i give the path for the application in the test.js:
```
...
  beforeEach(function () {
    return helpers.startApplication({

      args:[path.join(__dirname, '..')] 
    }).then(function (startedApp) { app = startedApp })
  })
...
```

**Comment by bendemboski** [comment]
@devinaction I think what you want to do is run `ember electron:package` and then point `spectron` to your packaged app, like in the "Getting Started" example [here](https://electron.atom.io/spectron/). The packaged app will be in `electron-out` in a sub-folder named according to your platform/architecture.

**Comment by HabibulHH** [comment]
@bendemboski  , so what we use as a path  ? already packaged folder ? that exsists inside electron-out ? 
var app = new Application({
  path: '/Applications/MyApp.app/Contents/MacOS/MyApp'
})

**Comment by bendemboski** [comment]
@HabibulHH whenever you want to run your `spectron` tests, you would first run `ember electron:package`, then specify the path to the binary inside `electron-out`, whose path depends on your OS. For example on MacOS it would be `electron-out/MyApp-darwin-x64/MyApp.app/Contents/MacOS/MyApp`.
