### ISSUE TITLE
ember electron:test --serve hangs on reload

### ISSUE THREAD

**Issue by seansellek** [felixrieseberg/ember-electron#307]
On a fresh install of Ember with ember-electron,  `ember electron:test --serve` loads the electron renderer and runs the tests, but when a file is changed, the renderer attempts to refresh and instead hangs on a blank screen, with the tests never indicating they are rerun.

Steps:

```
ember new test-electron
cd test-electron
ember install ember-electron
ember electron:test --serve
```

Then trigger a restart by saving a file. Test browser will hang on blank screen. 

Ember-cli: 2.14.2
Ember-electron: 2.3.1
macOS Sierra 10.12.6

Please let me know if any more information is needed or if I can take any steps to help identify the source of this issue.

**Comment by anulman** [comment]
@seansellek So sorry this went unresponded. Can you / @debelop13 / @jchen9773 elaborate if this is still an issue? I've certainly seen this behavior before, but not recently.
