### ISSUE TITLE
socket.io 1.3.5 dependencies fail to build on Windows

### ISSUE THREAD

**Issue by nselikoff** [felixrieseberg/ember-electron#31]
First off, thanks for this addon, it's exactly what I need and will save me a huge amount of time!

I'm on Windows 8.1 x64 with npm 3.7.2 and node v5.6.0, and the installation was failing when trying to compile the `ws` node package for socket.io 1.3.5. Ultimately the issue was solved by editing ember-electron's package.json to use socket.io 1.3.6, which I tried after reviewing this issue: https://github.com/socketio/socket.io/issues/2056

So I recommend updating the project's dependencies to `"socket.io": "^1.3.6",` as long as that doesn't mess with anything else.

**Comment by felixrieseberg** [comment]
...fixed, version bumped, and updated. Thanks for letting me know!
