### ISSUE TITLE
Configurable Yarn and NPM

### ISSUE THREAD

**Issue by xn** [felixrieseberg/ember-electron#312]
Can we expose some configuration or override for the usage of npm and yarn? I had to delete yarn from my windows box to get one project to make.

Thanks.

**Comment by pichfl** [comment]
Yarn detection should rely on the same mechanisms ember-cli uses, so if you don't have a `yarn.lock` in the project, it should default to npm. You should be able to force this by using the `--no-yarn` flag.

**Comment by xn** [comment]
Ok, hasYarn is used here:
https://github.com/felixrieseberg/ember-electron/blob/5c867a77464dcc875f8e35b9b2d30fddd60a2adf/lib/tasks/assemble.js#L67

hasYarn merely checks for the existence of the yarn command as seen here:
https://github.com/camacho/yarn-or-npm/blob/master/index.js#L9

Is there something I am missing that brings the yarn.lock into the equation here?

**Comment by pichfl** [comment]
Oh sorry for leading you on with this. I wasn't quite involved with that part of the addon, maybe @bendemboski can be of more assistance.

**Comment by xn** [comment]
No worries.
