### ISSUE TITLE
socket.io.js and ember_debug.js should not be injected in a production build

### ISSUE THREAD

**Issue by nselikoff** [felixrieseberg/ember-electron#32]
Running `ember electron:package` (defaults to production env, right?) or `ember electron -prod`, the addon injects socket.io.js, the io inline bootup code, and ember_debug.js into the header, but since it doesn't start the debug server, those end up being failed load requests, as seen in the console:

````
http://localhost:30820/socket.io/socket.io.js Failed to load resource: net::ERR_CONNECTION_REFUSED
index.html:36 Uncaught ReferenceError: io is not defined
\resources\atom.asar\renderer\lib\init.js:75 Uncaught TypeError: Cannot read property 'listeners' of undefined
http://localhost:30820/ember_debug.js Failed to load resource: net::ERR_CONNECTION_REFUSED
````

**Comment by felixrieseberg** [comment]
Thanks, that makes a lot of sense - it's fixed in 0.5.6. Thanks for reporting!
