### ISSUE TITLE
Question: How to access environment information in production

### ISSUE THREAD

**Issue by davydany** [felixrieseberg/ember-electron#322]
When running `ember electron:make`, it can take an optional `--environment=<environment>` flag. This value is accessible in the renderer process from ember with:

```javascript
import config from '../config/environment';

console.log("Environment: ", config.environment);
```

How do I access this environment variable from the main Process, for example from the `/ember-electron/main.js` file?

**Comment by felixrieseberg** [comment]
I don’t think that’s possible, because Ember’s environment isn’t the *real* environment - and because it’s hidden away in a bundle.

I’d suggest using the real environment on `process.env` and inheriting it in Ember’s config file.
