### ISSUE TITLE
Specify icon file as command line arguments

### ISSUE THREAD

**Issue by edmoresamewave** [felixrieseberg/ember-electron#325]
electron packager enables one to specify the icon file as command line arguments like how you can with electron packager "--icon", is this possible using electron:package? the help command shows it as not available? Is there some other way to do this, besides applying some sort of after hooks to replace or copy icons across. 

I know I can specify the icon file in the config but I would like to use different icons in my builds.

**Comment by bendemboski** [comment]
@edmoresamewave the config file is the only way to specify the icon now, but you can read environment variables from the config, so you could use the environment to switch between different icons.
