### ISSUE TITLE
App closes after entering first character in debug console

### ISSUE THREAD

**Issue by Mithrilhall** [felixrieseberg/ember-electron#333]
Created a new electron project and uncommented the dev tools in main.js.

`mainWindow.openDevTools();`

Typing into the console drawer causes the application to close.

**OS**: Linux Mint 18.2 (KDE 64-bit)
**Ember-cli**: 2.18.0
**Ember-Electron**: 2.7.2

**navigator.appVersion**: 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) test-me/0.0.0 Chrome/59.0.3071.115 Electron/1.8.2-beta.3 Safari/537.36

**Comment by Mithrilhall** [comment]
[Related?](https://github.com/felixrieseberg/ember-electron/issues/333)

**Comment by bendemboski** [comment]
@Mithrilhall it definitely looks like you're hitting that Electron issue -- multiple comments on that thread report seeing the issue in `Electron 1.8.2-beta.3` on linux. You can modify your `package.json` to use a different version of `electron-prebuilt-compile` (which corresponds directly to the `Electron` version you end up with), so maybe try `1.8.1` or earlier?

In any case, this doesn't look like it's an issue with `ember-electron`, so I'm going to close it.

**Comment by Mithrilhall** [comment]
Thanks @bendemboski. I'll give that a shot.
