### ISSUE TITLE
[Question] Can I send information from electron (main.js) to ember?

### ISSUE THREAD

**Issue by debelop13** [felixrieseberg/ember-electron#334]
Hi!

I need to check if app comes from a suspend.

I found 'on resume' event in electron: https://github.com/electron/electron/blob/master/docs/api/power-monitor.md

But I don't know how call a ember method, or call a service or call something of ember? It is possible?

Thanks!

**Comment by bendemboski** [comment]
@debelop13 you'd need to use the IPC mechanism. To do that, implement an Ember service that uses the [ipcRendered](https://github.com/electron/electron/blob/master/docs/api/ipc-renderer.md) interface to set up a listener for events from the main process. Then, in the main process you can your window's [webContents](https://github.com/electron/electron/blob/master/docs/api/web-contents.md), which is an `EventEmitter` to send an event to the renderer process.

**Comment by rwwagner90** [comment]
@bendemboski do you have any examples handy of setting up passing data between electron and Ember?

**Comment by bendemboski** [comment]
@rwwagner90 nothing open source, but if you can describe your use case, I can probably throw together some sample code pretty quickly.

**Comment by rwwagner90** [comment]
@bendemboski I just tried to import it in my controller and it says it cannot find electron.

```js
import { ipcRenderer } from 'electron';
```

**Comment by bendemboski** [comment]
Right, so you have to access electron as a node module, not an Ember-transpiled ES6 module. So you'd need to us syntax like this:

```javascript
const { ipcRenderer } = requireNode('electron');
```

You want to use `requireNode()` instead of the standard `require()` as explained [here](https://github.com/adopted-ember-addons/ember-electron/blob/master/docs/guides/usage.md#conflict-between-ember-and-electron-require).

**Comment by rwwagner90** [comment]
Thanks @bendemboski! Are there any plans to perhaps use ember-cli-addon-docs to document this project? I've been learning a lot so far, but could be helpful for the next person.

**Comment by bendemboski** [comment]
Not really, this isn't being super actively maintained right now. Probably when `electron-forge` 6 finally makes it out of beta, I/we will make some time to do a bunch of updates and perhaps re-visit the documentation, but for now what we have is [here](https://ember-electron.js.org/).

**Comment by rwwagner90** [comment]
@bendemboski I wouldn't mind helping move those docs into an addon docs app, if you guys are open to that.

**Comment by bendemboski** [comment]
Yeah, sounds great to me! The guy that wrote the current docs isn't really involved much anymore, so I'd certainly be happy for some doc updates!
