### ISSUE TITLE
Using ember-electron's window globals with TypeScript

### ISSUE THREAD

**Issue by perlun** [felixrieseberg/ember-electron#338]
Since around the time of #246, `ember-electron` works great together with TypeScript, using the [`ember-cli-typescript`](https://github.com/typed-ember/ember-cli-typescript) addon. No problems.

_However_, since the configuration in my project doesn't know about `ember-electrons` particular setup, the following globals are detected as "invalid", with squiggles in the editor etc:

- window.moduleNode
- window.processNode

Is there a way to make these globals known to TypeScript? Maybe @chriskrycho has an idea?

(I know this is not an issue with ember-electron per se, but with the particular combination "ember-electron + ember-cli-typescript". However, it makes sense to keep it in this repo for documentation/discoverability purposes, so please do not close it too quickly.)

Thanks for a great addon. 👍

**Comment by chriskrycho** [comment]
@perlun this declaration (anywhere in your project, but probably in something like `electron.d.ts`) will fix the immediate problem:

```ts
declare global {
  moduleNode: any;
  processNode: any;
}
```

Beyond that, [these typings](https://www.npmjs.com/package/electron-typescript-definitions) look like they’ll probably be helpful.

**Comment by perlun** [comment]
Thanks @chriskrycho. That gives me this:

<img width="910" alt="image" src="https://user-images.githubusercontent.com/630613/36614124-58d85e48-18e4-11e8-8ff0-cda3fd008d48.png">

What did I do wrong? (I put these in a file named `types/notime/electron.d.ts` in my project.)

**Comment by perlun** [comment]
@chriskrycho Any ideas?

**Comment by chriskrycho** [comment]
Add `export {}` to that file. That should solve that problem at least. Sorry for the delayed response!

**Comment by perlun** [comment]
Thanks, it didn't work OOTB but this helped me to finally get it working:

```typescript
declare global {
    interface Window {
        moduleNode: any;
        processNode: any;
    }
}

export {};
```

However, the TypeScript compiler didn't pick that file (`types/notime/electron.d.ts`) up automatically; it turned out I was missing the `types` folder in the `include` section in my `tsconfig.json`:

```json
  "include": [
    "app",
    "tests",
    "types"
  ]
```

Now it works perfectly - thanks for all your help! 👍 👍 👍
