### ISSUE TITLE
Proxy `requireNode` & `processNode` when running outside electron?

### ISSUE THREAD

**Issue by jacobq** [felixrieseberg/ember-electron#345]
This is partly a feature request and partly a request for feedback about this idea. While I do most of my development running `ember electron` and `ember electron:test` I sometimes wish I could run `ember s` and try access it with Chrome canary. Unfortunately, my app makes heavy use of node, e.g. an important instance-initializer needs to read files. I know that, at least in theory, it should be possible to decouple all of the node things, e.g. if `requireNode` is not a function then define it to be one and have it return mock modules with stuffed data, etc. However, I think it would be cool if instead things like `requireNode` could be like RPCs passed over WebSockets to the ember-cli (node) side, executed there, and the results passed back so the app doesn't know the difference.

- Is this a bad idea? If so, how bad & why?
- Any guesses as to how hard this would be to implement?
- Perhaps this is outside of the scope of ember-electron. Would a generalized version of this be applicable elsewhere? (Are people already doing stuff like this elsewhere?)

**Comment by bastientanesie** [comment]
I'd like to see this feature implemented too!  
I'm currently building an ember app that needs to work inside of electron as well as outside of it. I don't know how to tackle this ATM (besides ignoring _"`requireNode` is not defined"_ messages)...

Is there any workaround for those situations (while we wait for some kind of proxy implementation)?

Poke @felixrieseberg @anulman

**Comment by bastientanesie** [comment]
@bendemboski that's basically what I thought about. Thanks a lot for your feedback!  
And apologies @jacobq for moving away from the base topic =/. I'm still interested in this though.

**Comment by jacobq** [comment]
I'm closing this due to loss of (my) interest, but if someone else wants to pursue the idea then feel free. While this might be a sort-of cool, whiz-bang feature, it's more of a parlor trick and might actually increase confusion by making things possible in a browser during development that won't work in a non-electron, production environment. If an app is intended to run in both electron and standard browser contexts then the solution that Ben outlined is a reasonable way to do it. As for what I wanted (e.g. being able to see how my app would run in a future version of electron that used newer Chromium and/or newer Node), it should be possible just by improving the modularity / separation of concerns of my code. In other words, avoiding coupling "front-end" and "back-end" functionality.
