### ISSUE TITLE
stop task bar form moving

### ISSUE THREAD

**Issue by starkapps** [felixrieseberg/ember-electron#347]

**Comment by bendemboski** [comment]
@starkapps there's no info in this ticket -- did you open it accidentally? I'm going to close it, but if you're trying to report an issue, feel free to re-open and provide some info.

**Comment by starkapps** [comment]
Sorry, that was an accident, feel free to remove! 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ben Demboski <notifications@github.com> Date: 4/9/18  10:14 AM  (GMT-08:00) To: felixrieseberg/ember-electron <ember-electron@noreply.github.com> Cc: starkapps <starkartsapps@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [felixrieseberg/ember-electron] stop task bar form moving (#347) 
@starkapps there's no info in this ticket -- did you open it accidentally? I'm going to close it, but if you're trying to report an issue, feel free to re-open and provide some info.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/felixrieseberg/ember-electron","title":"felixrieseberg/ember-electron","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/felixrieseberg/ember-electron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bendemboski in #347: @starkapps there's no info in this ticket -- did you open it accidentally? I'm going to close it, but if you're trying to report an issue, feel free to re-open and provide some info."}],"action":{"name":"View Issue","url":"https://github.com/felixrieseberg/ember-electron/issues/347#issuecomment-379826287"}}}
