### ISSUE TITLE
Missing tag/release 2.8.0 and changelog

### ISSUE THREAD

**Issue by bastientanesie** [felixrieseberg/ember-electron#350]
NPM references [a version 2.8.0](https://www.npmjs.com/package/ember-electron/v/2.8.0) as the latest `ember-electron` version, but there is no tag/release matching this version on github. Did I missed something?

Also, it seems like this project does not have a changelog 😞. Would have been nice to spot differences between 2.7.3 (last tag on github) and 2.8.0.  
Any plans to add one?

**Comment by felixrieseberg** [comment]
Momentary hickup, that was my fault - I forgot to push after releasing. The tag is now live.

I get your request for a changelog, I'll see what I can do about that.
