### ISSUE TITLE
Sporadic blank app

### ISSUE THREAD

**Issue by john-griffin** [felixrieseberg/ember-electron#36]
When starting a basic app (either packaged or from ember-cli) based on the blueprint I occasionally just get a completely blank app. In the dev console I get the error `Not allowed to load local resource`

<img width="1210" alt="screen shot 2016-02-18 at 10 21 14" src="https://cloud.githubusercontent.com/assets/19490/13148316/d1b4212a-d62a-11e5-9297-24fed3a0b5c0.png">

Restarting fixes this but it will come back sporadically. Any idea what this could be? Not sure if its ember-electron specific.

**Comment by john-griffin** [comment]
I have temporarily solved this by adding the following to my `electron.js`

``` js
mainWindow.webContents.on('did-fail-load', () => {
  mainWindow.loadURL('file://' + __dirname + '/dist/index.html');
});
```

Not ideal but it rescues the app from total failure.

**Comment by felixrieseberg** [comment]
Interesting, thanks for letting me know - I might just move that bit into the default `electron.js`, given that we should probably capture that event anyhow.

**Comment by felixrieseberg** [comment]
Thanks again - this is now in `electron.js` by default (as of 0.5.7).

**Comment by gordonbisnor** [comment]
@felixrieseberg Thanks for the EmberConf talk! I had to abandon an nw.js app due to lack of codec support, excited to see that Electron may make it possible.

I had an issue installing ember-electron, was getting __dirname is not defined error. 
This worked for me: 

**ember-electron/blueprints/ember-electron/files/electron.js, line 7:**

```javascript
const emberAppLocation = `file://./dist/index.html`;
```
**instead of:**

``javascript
const emberAppLocation = `file://${__dirname}/dist/index.html`;
```

Not sure if it's just me –– perhaps because I'm not running the latest release of Node or etc....

Any thoughts on this?

**Comment by felixrieseberg** [comment]
Hey, it's most certainly the version of Node - I'd recommend running at least 5, which is the version with which Electron will execute your code once bundled. That way, you (the developer) and the users are running the same version of Node ;-)

Also, thanks for the nice comments!

**Comment by gordonbisnor** [comment]
Strange –– when I run node -v I'm seeing v5.7.1

**Comment by felixrieseberg** [comment]
That is super strange... can you fire up the repl and just run `console.log(__dirname)`? It's supposed to be a Node global :)

**Comment by gordonbisnor** [comment]
Yeah I tried that too in the process of debugging, and I get this:

```node
> console.log(__dirname)
ReferenceError: __dirname is not defined
    at repl:1:13
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:431:12)
    at emitOne (events.js:95:20)
    at REPLServer.emit (events.js:182:7)
    at REPLServer.Interface._onLine (readline.js:211:10)
    at REPLServer.Interface._line (readline.js:550:8)
    at REPLServer.Interface._ttyWrite (readline.js:827:14)
```

**Comment by felixrieseberg** [comment]
I feel like your Node is borked, I'd try reinstalling it (https://nodejs.org/docs/latest/api/globals.html#globals_dirname) - if that global isnt' there, who knows what else is broken...

**Comment by gordonbisnor** [comment]
Ah okay thanks I will try that!

**Comment by gordonbisnor** [comment]
Strange, I tried brew uninstall node, then reinstalled with brew, did not work. Then I tried uninstalling the brew version and tried the node package at 5.10.0 and I'm still getting the same problem. I realize that this may not be an ember-electron issue, but thanks at any rate for the advice Felix!

**Comment by gordonbisnor** [comment]
I see on StackOverflow someone mentioned that `__dirname is only defined in scripts. It's not available in REPL.`  –– I tried writing and running a script where I logged out the __dirname and that worked just fine.
