### ISSUE TITLE
Firebase incompatibility?

### ISSUE THREAD

**Issue by AlekzZz** [felixrieseberg/ember-electron#361]
Firebase throws error:

{
  code: "auth/operation-not-supported-in-this-environment",
  message: "This operation is not supported in the environment this application is running on. "location.protocol" must be http, https or chrome-extension and web storage must be enabled."
}

this is because ember-electron is using "electron-protocol-serve" and `location.protocol` is "serve:", I used ember-electron with firebase previously on different project and it was working fine, this looks like something new.

**Comment by felixrieseberg** [comment]
You can easily change the protocol, if you feel like another protocol is more appropriate. That said, this is only fixable in Firebase - because if I read this message correctly, `file://` isn't even allowed.

I'd recommend reporting to Google and mentioning Electron as a usecase.
