### ISSUE TITLE
Error: The "path" argument must be of type string

### ISSUE THREAD

**Issue by christophersansone** [felixrieseberg/ember-electron#362]
Occurring with:

* ember-electron 2.9.0
* ember-cli 2.15.1
* node 9.x (also tried node 7.x)

After installing EE, I simply ran `ember electron` and got the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.join (path.js:1158:7)
    at Builder._unsymlinkModules (app/node_modules/ember-electron/lib/models/builder.js:55:26)
    at Builder.copyToOutputPath (app/node_modules/ember-electron/lib/models/builder.js:42:10)
    at Promise.resolve.then (app/node_modules/ember-cli/lib/models/builder.js:118:24)
...
```

It seems to be complaining about the `outputPath` being undefined, but specifying `--output-path` on the command line had no effect.

With some help on the Slack channel, I discovered that the problem is here: https://github.com/felixrieseberg/ember-electron/blob/159415a248014cd53fc3612da833939056252f9a/lib/commands/electron.js#L18-L47 .  If I change it to call `_super` at the end of the function, it works.  It appears that `availableOptions` needs to be specified prior to the base class constructor.

It appears that this commit is the culprit (and is therefore isolated to 2.9.0): https://github.com/felixrieseberg/ember-electron/commit/2b2047b468008dd27920b828bbc29bd197b79ce6

I'm assuming it must work in other versions of `ember-cli`, but I don't see anything in its changelog that might have impacted it.

**Comment by jacobq** [comment]
Sorry, I didn't realize I introduced a regression. I was trying to address the [`avoid-leaking-state-in-ember-objects`](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/avoid-leaking-state-in-ember-objects.md) warning. I did not see any problems in CI or in my environment (node 10.x, ember 3.x, x86_64 Linux). Thanks for digging in and reporting this problem.
