### ISSUE TITLE
CSS images not loading

### ISSUE THREAD

**Issue by Frozenfire92** [felixrieseberg/ember-electron#37]
Any images defined in css via

```css
background-image: url('/assets/images/icon.png') ;
```

do not get loaded. Is there a workaround to this?

**Comment by wkurosawa** [comment]
Hey @Frozenfire92 I was having the same problem, then I tried to use a different approach to set the relative path. 
Instead of `url('/assets/images/icon.png')` I used `url('../assets/images/icon.png')`. 

That worked for me. Can you try?

**Comment by Frozenfire92** [comment]
Worked for me as well! Thank you

**Comment by wkurosawa** [comment]
Good to know :-) 
Well, it doesn't seem to fit in any documentation, but at least anybody with questions about assets path in CSS will end looking at issues. 

@Frozenfire92 can you close this issue?
