### ISSUE TITLE
"Cannot find module" error thrown when using cjs require's in components

### ISSUE THREAD

**Issue by egee-irl** [felixrieseberg/ember-electron#376]
A generic "Cannot find module component_name" error is thrown when node modules are used in components. I'm pretty new to Ember and Electron development however I found [guides](https://www.bignerdranch.com/blog/ember-js-and-electron-build-desktop-apps-with-web-technologies/) showing the usage of this pattern so it worked at some point.

For my use case, I want to use the fs module so my Electron app can access files on the file system - a very typical use case. In order to do this, I need to import the fs module. This issue is preventing me from doing that.

For my test case I used the standard Ember "handling-events" [guide](https://guides.emberjs.com/release/components/handling-events/) on the website to create a component and trigger it. In the component, I added `const os = require("os");` which cause this error.

**Comment by bendemboski** [comment]
Have you tried `requireNode("os")`?

**Comment by bendemboski** [comment]
https://github.com/felixrieseberg/ember-electron/blob/master/docs/guides/usage.md#conflict-between-ember-and-electron-require

**Comment by egee-irl** [comment]
Ah, yes that appears to have fixed it. I read that section when I was starting out but I thought it was referring to something else. Thanks for your response! :+1:
