### ISSUE TITLE
Fullscreen on linux not working on build

### ISSUE THREAD

**Issue by Frozenfire92** [felixrieseberg/ember-electron#38]
On `ember electron` I can go fullscreen with `F11` or through the menu. However on a built app the keyboard shortcut does not work. The built app does work on OSX for full screen however.

**Comment by felixrieseberg** [comment]
Did you setup the `menu`? When you run `ember electron`, you're getting a default menu, which is not the case for packaged apps. You can find the info here: https://github.com/atom/electron/blob/master/docs/api/menu.md

**Comment by Frozenfire92** [comment]
I did not, I assumed fullscreen would have worked without a menu (menu was not ideal in this application. Thanks for the heads up!

**Comment by felixrieseberg** [comment]
Cool, I'll close this in the meantime!
