### ISSUE TITLE
IPC not working in packaged app

### ISSUE THREAD

**Issue by Zeman97** [felixrieseberg/ember-electron#382]
Just as the title says, it seems my IPC isn't functioning in the packaged version of the app.

Just doing some testing in an app that only has one route and this is what I've got set up:

controller.js
```js
import Controller from '@ember/controller';
const { ipcRenderer } = requireNode('electron');

export default Controller.extend({
  init() {
    console.log('init');
    ipcRenderer.on('message', (event) => {
      console.log('message');
    });
    this._super(...arguments);
  }
});
```

_NOTE: I am using `requireNode()` because `require()` was not working for me although `requireNode()` says it is not defined in the compiler, so I am not sure what is going on with that._

main.js (snippet)
```js
mainWindow.webContents.on('did-finish-load', () => {
  mainWindow.webContents.send('message');
});
```

Whenever I run the app using `ember electron` the console has the expected output, but whenever I build the app using `ember electron:package` and run the executable, the console is empty.

Other UI elements which are displaying the message status are also not updated in the packaged version when they are in the live version.

It seems something about the packing process is breaking something.

**Comment by jacobq** [comment]
I highly suspect that what you are seeing is a race condition. You can test this by periodically sending messages like this, e.g.

```js
mainWindow.webContents.on('did-finish-load', () => {
  let i = 1;
  setInteveral(() => {
    console.log(`Sending IPC message #${i}`)
    mainWindow.webContents.send(`message #${i}`);
  }, 1000);
});
```

The `did-finish-load` event does not guarantee that your controller has been initialized.

**Comment by jacobq** [comment]
BTW, regarding `requireNode` you'd need to configure your linter to recognize that it's global -- this isn't yet handled by this addon. See also the [usage doc](https://github.com/felixrieseberg/ember-electron/blob/dd9227aa5913e46658718b40143f6630edab996e/docs/guides/usage.md#conflict-between-ember-and-electron-require)

**Comment by Zeman97** [comment]
Awesome thanks for the info! I am at work currently, but I will check these things whenever I get home and report back here.

**Comment by Zeman97** [comment]
@jacobq your suggestion about the IPC was correct! Thanks so much for the help, I'm going to close this issue now. Thanks again!
