### ISSUE TITLE
Development server?

### ISSUE THREAD

**Issue by sohara** [felixrieseberg/ember-electron#4]
A few questions. On this line: https://github.com/felixrieseberg/ember-electron/blob/master/blueprints/ember-electron/files/electron.js#L21, there is reference to a development server on port 5000. This doesn't seem to run by default?

Also, most ember apps involve API requests to server, often with a relative path. That appears to breaks since with ember-electron we are dealing with a `file://` protocol? Is there a way to get around that, that you know of?

**Comment by felixrieseberg** [comment]
Hey, the dev server is only invoked if you set the environment variable right in front of it - otherwise, it'll go with the file protocol. If you want to get around that, you could try working with `base`?
