### ISSUE TITLE
Changing output dir

### ISSUE THREAD

**Issue by oskarrough** [felixrieseberg/ember-electron#42]
Hi, how can you change the output dir? I'd like to use `dist-electron` instead of `electron-builds`.

**Comment by felixrieseberg** [comment]
Hey, not yet, but I'd love to merge a pull request that adds that. You'd just have to change [this line](https://github.com/felixrieseberg/ember-electron/blob/master/lib/commands/package.js#L257) to use an option you can add [right here](https://github.com/felixrieseberg/ember-electron/blob/master/lib/commands/package.js#L20). Would you be interested?

**Comment by oskarrough** [comment]
Looking through the code, there's already an `out` option which works just fine. Missed it! :+1:
