### ISSUE TITLE
Build fails for Windows

### ISSUE THREAD

**Issue by ksnyde** [felixrieseberg/ember-electron#44]
Probably a newbie error but I built my "hello world" app and ran `ember electron:package` but it fell over after packaging linux executable and I think right as it started windows:

> Packaging app for platform win32 ia32 using electron v0.36.2

> Error packaging your Ember app into an Electron executable:

> Error: spawn wine ENOENT
spawn wine ENOENT
Error: spawn wine ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)

**Comment by felixrieseberg** [comment]
Hey! When you don't specify the platform, we'll attempt to build on all platforms. I assume you're on Linux or OS X, meaning that the package is looking for Wine, which is apparently not installed.

Simple fix: Run `ember electron:package --platform darwin`!

**Comment by ksnyde** [comment]
No I wanted to build for all platforms. I actually did install wine after raising this issue and was going to close but I think it would be a good idea to mention somewhere in the documentation that this dependency exists.
