### ISSUE TITLE
Existing Ember project not launching with `ember electron`

### ISSUE THREAD

**Issue by kdawgwilk** [felixrieseberg/ember-electron#51]
Here is my current versions

package.json electron dependency versions
"electron-packager": "6.0.0",
"electron-prebuilt": "0.37.5",
"electron-rebuild": "1.1.3",
"ember-electron": "1.3.2",

$ ember -v
ember-cli: 2.4.3
node: 4.4.2
os: darwin x64

After running `ember install ember-electron` and configuring project trying to run `ember electron` gives me this:

![screen shot 2016-04-07 at 11 47 08 pm](https://cloud.githubusercontent.com/assets/7799267/14375128/4207269a-fd1b-11e5-970d-a1daee270336.png)

**Comment by kdawgwilk** [comment]
Also after  running `ember electron:package --platform darwin` and trying to launch app I get this

![screen shot 2016-04-07 at 11 56 55 pm](https://cloud.githubusercontent.com/assets/7799267/14375252/c494c3b4-fd1c-11e5-8024-acbbb2e53543.png)

**Comment by felixrieseberg** [comment]
Thanks for reporting! I'ts a bit hard to see because of the whiteouts, but is there a comma in the app name? I'd assume that the trouble is that the app and the generator disagree over where the app is located. To fix:

 * In `package.json`, ensure that all names are filesystem-compliant (ideally: A-Z;0-9)
 * Check your filesystem, especially electron-builds. Where is the app?

**Comment by felixrieseberg** [comment]
Oh, and if you changed your app's name, you should probably run ember g ember-electron again.

**Comment by kdawgwilk** [comment]
Yeah sorry about the white out 😁 those are actually the letter y and the name is made up of just letters and - ? Any other ideas?

**Comment by felixrieseberg** [comment]
It's definitely the app name - or, if you're sure that the files are there on disk, you might have an error in that file that keeps it from being successfully exported.

**Comment by kdawgwilk** [comment]
Which file would have the error? `electron.js`?

**Comment by SSS2557** [comment]
for me, with the same versions and OS, the electron app is just shown in the dock but no app window pops up :(

No errors too. I tried packaging it and opening the executable but still the same.

**Comment by kdawgwilk** [comment]
I also was able to run the tests fine not sure why one would run and the other not

**Comment by anulman** [comment]
Closing due to age; please do reopen if this is still an issue 😄
