### ISSUE TITLE
Use existing dev node_modules for production

### ISSUE THREAD

**Issue by devlo** [felixrieseberg/ember-electron#52]
Could you make additional option like --use-dev-node_modules or direct me where i could change it myself? Because now every time i package my app, ember-electron is downloading packages (from dependencies in package.json) again, some of them are node native extensions, so it's compiling them every time.

EDIT: One more thing, while selecting --version=0.37.5 i get info "Installing Electron headers for version 0.37.3" while using 0.37.5

EDIT2: This is the function that install dependencies right?
https://github.com/felixrieseberg/ember-electron/blob/master/lib/commands/package.js#L203

**Comment by felixrieseberg** [comment]
It's a good idea, I'd certainly love to see a Pull Request for that. You already found the right function, maybe you want to take a crack at it?

For the recompilation: We just check what your precompiled version is. Here, too - if you want to make an override parameter, I'd love to merge it!

**Comment by devlo** [comment]
@felixrieseberg 

Ok i will try to crack at it and make PR ;)

**Comment by devlo** [comment]
Ok, everthing works fine, just need to figure out a way to not to recompile native dependencies, i don't see any filter there in electron-rebuild. Any ideas? or just hack around it with filtering dir list?

**Comment by devlo** [comment]
Ok i have changed everything to make copy after native dependency recompiling. Will do PR soon.

**Comment by devlo** [comment]
here is PR https://github.com/felixrieseberg/ember-electron/pull/53
