### ISSUE TITLE
Unable to set icon for windows

### ISSUE THREAD

**Issue by ajainvivek** [felixrieseberg/ember-electron#57]
Throws error in CLI: Unable to set icon

Steps followed:

1. Installed Wine
2. Updated package.json with icon
```
//package.json

"ember-electron": {
    "copy-files": [
      "package.json",
      "main/*"
    ],
   "icon": "assets/icons/p2pdrop"
}
```

**Comment by ajainvivek** [comment]
Can anyone help here 

Packaging app for platform win32 ia32 using electron v0.37.7
Error packaging your Ember app into an Electron executable:
Fatal error: Unable to set icon

Even for mac it doesn't work

**Comment by felixrieseberg** [comment]
Hey, can you share your icon? I can't think of much, but that's the only thing I can think of. In addition, does it work fine if you don't try to set an icon?

**Comment by ajainvivek** [comment]
@felixrieseberg it works fine without icon. For reference i copied icons from ghost app even then the icon doesn't reflect on the builds. 

package.json has exact reference to the path as well

**Comment by fredguth** [comment]
Just to leave a note for anyone looking for a solution to the problem.  The .ico should be 256x256 to be accepted

**Comment by Ghost---Shadow** [comment]
I resized. Problem persists.
