### ISSUE TITLE
Ember app is not loaded to the Electron

### ISSUE THREAD

**Issue by dulichan** [felixrieseberg/ember-electron#58]
I have this weird scenario where the ember app is not loaded inside the electron app. I am not getting any kind of errors. I am attaching a screenshot of this. 
<img width="995" alt="screen shot 2016-04-25 at 11 34 04 pm" src="https://cloud.githubusercontent.com/assets/1016598/14806045/425246e4-0b3e-11e6-96c0-d27fc0019224.png">

This is what comes up when I run ember electron

<img width="1228" alt="screen shot 2016-04-25 at 11 34 15 pm" src="https://cloud.githubusercontent.com/assets/1016598/14806047/4307c848-0b3e-11e6-833d-04dcaff471ff.png">

This is what the developer console is saying. 

I reverted back to an old project to see if my code changes have caused this - but it seems not the case. I haven't updated the ember version either. Below are my versions

```
"devDependencies": {
    "broccoli-asset-rev": "^2.2.0",
    "electron-packager": "5.2.1",
    "electron-prebuilt": "0.36.10",
    "ember-ajax": "0.7.1",
    "ember-bootstrap": "0.6.3",
    "ember-browserify": "1.1.8",
    "ember-cli": "2.3.0-beta.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.5",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-font-awesome": "1.5.0",
    "ember-cli-htmlbars": "^1.0.1",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-qunit": "^1.2.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-sri": "^2.0.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.3.0",
    "ember-disable-proxy-controllers": "^1.0.1",
    "ember-electron": "1.1.1",
    "ember-export-application-global": "^1.0.4",
    "ember-inspector": "1.9.5",
    "ember-load-initializers": "^0.5.0",
    "ember-resolver": "^2.0.3",
    "loader.js": "^4.0.0"
  },
  "main": "electron.js",
```

**Comment by felixrieseberg** [comment]
The renderer seems to crash very early on - but before we debug that, maybe try updating your `electron-prebuilt` version. Let me know how things work out with `0.37`!

**Comment by dulichan** [comment]
I updated the version to 0.37 but still no use. Can you please tell me how I can debug this? Since I am not able to see any errors on the console, I can't seem to get my hands into what's actually causing this. 

Thanks

**Comment by dulichan** [comment]
Hi guys,
New findings - I created a new ember project, reinstalled ember electron and added all my files. It was working fine. But after sometime -again it's crashing. Have we disabled logs when the render crashes in ember electron? 

Can I run plain electron without ember electron to get the logs? 

Cheers~

**Comment by felixrieseberg** [comment]
It sadly won't give you more logging - when the renderer crashes hard, so does everything in it... This might be obvious, but I assume the app runs just fine in Chrome?

Are you doing anything native?

**Comment by dulichan** [comment]
Yeh - the app runs fine in chrome. I even made a vanilla electron app and included the dist folder in there. The app gets loaded. One of the things I am doing is that I am storing some web content to localStorage. Is this a problem? 

Cause after I moved everything to a new ember location it worked for a while. Only after about a day it started crashing. I tried deleting node_modules and bower_components but no luck. 

Anything special being done on electron when calling `ember electron` ?

**Comment by felixrieseberg** [comment]
No, absolutely nothing. I really want to help you, but I have no idea what the reason could be - maybe nuke your local storage for good measure? You can find it in %APPDATA% on Windows and in ~/Library/Application Support on OS X.

**Comment by dulichan** [comment]
Thanks man! Really appreciate it. So the problem was due to the local storage. I thought the localStorage is getting wiped out every time I close the app (since it was development environment. 

For anybody else who might face this problem - in Mac there will be a folder created inside the `~/Library/Application Support/{your_app_name}`. Delete the things in localStorage. 

Cheers~
