### ISSUE TITLE
How to avoid downloading platforms on ci

### ISSUE THREAD

**Issue by Suven** [felixrieseberg/ember-electron#59]
Hi!

I am developing an app where electron just happens to be just one of the possible targets.
The dev-cycle involves running the test-suite on every commit.

Unfortunately the ci downloads and install electrons platform-deps on every installation. Is there a way to download them ad-hoc (i.e. when building?)

**Comment by felixrieseberg** [comment]
Hey, thanks for asking. That's currently not possible - have you considered using Git submodules or a custom build script?

(I'm closing this in the meantime, since this won't be a feature of ember-electron)
