### ISSUE TITLE
CrashReporter error on first run

### ISSUE THREAD

**Issue by DiederikvandenB** [felixrieseberg/ember-electron#63]
Hi,

I installed a fresh copy of Ember and Ember Electron and I got an error when first running it:
`App threw an error when running [Error: companyName is a required option to crashReporter.start]`

I fixed it by changing the setting on rule number 13 in the `electron.js` file to:

```
electron.crashReporter.start({
  productName: 'productname',
  companyName: 'companyname',
  submitURL: 'http://localhost:30820'
});
```

Which fixes the issue. However, I don't understand why this issue occurs on a clean install of Ember. Furthermore, is the submitURL the correct one? It's the URL where Ember Inspector is running, but it seems like bad practice to hardcode it.

**Comment by makepanic** [comment]
This happens because of the [electron@1.0 release today](http://electron.atom.io/blog/2016/05/11/electron-1-0). 
The updated `crashReporter` now requires some fields, see https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md#crashreporterstartoptions

**Comment by DiederikvandenB** [comment]
That's what I expected yeah, noticed the modification date was only 12 hours ago. However, the other questions / issue still persist :).

**Comment by makepanic** [comment]
from reading the crash reporter docs, i think `submitURL` should point to a public server that accepts crash reports ([For setting up a server to accept and process crash reports, you can use following projects...](https://github.com/electron/electron/blob/master/docs/api/crash-reporter.md#crashreporter))

**Comment by anulman** [comment]
Closing, since @felixrieseberg's [commit May 12](https://github.com/felixrieseberg/ember-electron/commit/8c12a67e6c914ba5e85a3e9803d0f03d674a362d) accommodates for this
