### ISSUE TITLE
Can't require electron packages

### ISSUE THREAD

**Issue by DiederikvandenB** [felixrieseberg/ember-electron#64]
Hi!

So I am trying to get things to work, but after much Googling I wasn't able to find the answer. I started with a clean install of Ember and then I created a controller and route called `index`.

	import Ember from 'ember';
	const dialog = requireNode('electron').dialog;

	export default Ember.Controller.extend({
		actions: {
			'clickMe': function() {
				dialog.showErrorBox('Test', 'test');
			}
		}
	});

When I run this I will get an error saying that dialog is undefined: `Uncaught TypeError: Cannot read property 'showErrorBox' of undefined`. Any thoughts on what I am doing wrong?

In my terminal window I see the following message: `index/controller.js: line 2, col 16, 'requireNode' is not defined.` When I change `requireNode` to `window.requireNode` there's no difference.

Note: I do use Ember Pods structure, but I cannot imagine this has something to do with that.

**Comment by felixrieseberg** [comment]
Yeah, this is an easy one: Electron has a main thread - and renderer threads. You're in a renderer thread, but trying to call a method on the main thread. Easy solution:

```
const {dialog} = require('electron').remote;

// That's the same as...
const dialog = require('electron').remote.dialog;
```

**Comment by DiederikvandenB** [comment]
Thanks. I feel like an idiot now haha.

**Comment by felixrieseberg** [comment]
No worries, I prefer easy problems ;-)
