### ISSUE TITLE
Problems running tests on 1.5.1

### ISSUE THREAD

**Issue by john-griffin** [felixrieseberg/ember-electron#65]
Upgraded to 1.5.1 and Electron 1.0.1. When I run tests via `ember electron:test` I get an alert:

`Error: Cannot find module 'browser-window'`

I'm just using stock test config. Do the test blueprints need to be updated to support latest electron changes?

**Comment by felixrieseberg** [comment]
Thanks a lot for letting me know - the old tests blueprint needed an updated. I just pushed 1.5.2, which has that error fixed!

**Comment by john-griffin** [comment]
Thanks for the quick fix 👍
