### ISSUE TITLE
ember electron:package doesn't work anymore

### ISSUE THREAD

**Issue by wooandoo** [felixrieseberg/ember-electron#66]
Hello,

I updated my application with the 1.5.2 version of "ember-electron". And now "ember electron:package" doesn't work anymore for me.

To test this version and avoid mistakes with my application, I created a new "ember" application and I installed "ember-electron".

"ember electron" works
"ember electron:package" seems to work (no error), but the "electron-build" folder is not created as before

Do you have an idea of my error?

Frédéric

**Comment by felixrieseberg** [comment]
Thanks for the info - you're right, it's broken. The trouble is that `electron-rebuild` is apparently not ready to deal with Electron 1.0, I'll see if there's something we can do about that.

**Comment by felixrieseberg** [comment]
A fix is already on the way https://github.com/electron/electron-rebuild/pull/67

**Comment by felixrieseberg** [comment]
:warning: SOLUTION :warning:

Until this is fixed in our dependencies (which should happen within 24 hours or so), here's the manual fix: When running `ember electron:package`, headers will be downloaded. This download is currently failing, but you can place the files manually.

1) Download https://atom.io/download/atom-shell/v1.0.1/node-v1.0.1.tar.gz
2) Unzip to `LOCATION_OF_EMBER_ELECTRON/node_modules/electron-rebuild/lib/headers/.node-gyp/1.0.1/`

**Comment by wooandoo** [comment]
Thanks!! It works fine for me.

And thanks again for ember-electron. ;-)

`
cd node_modules/electron-rebuild/lib/headers/.node-gyp/
wget https://atom.io/download/atom-shell/v1.0.1/node-v1.0.1.tar.gz
tar xfz node-v1.0.1.tar.gz
mv node-v1.0.1 1.0.1

cd ../../../../..
ember electron:package --version 1.0.1 --platform darwin
`

**Comment by felixrieseberg** [comment]
This is now fixed in upstream!

**Comment by oligriffiths** [comment]
@felixrieseberg Hi, I just installed ember-electron, and I'm seeing this error when running `ember electron:package`:
```
Built project successfully. Stored in "./tmp/electron-build-tmp/dist".

Copying files into Electron Build folder
Copying electron.js
Copying package.json
Installing production dependencies into Electron Build Package
Recompiling native dependencies

Native compilation did not work:
Error: Could locate node-gyp
```

Is this still the same issue?

**Comment by ubuntuvim** [comment]
@oligriffiths I also encountered this problem, how do you solve?

**Comment by oligriffiths** [comment]
I've not solved it yet :(

**Comment by felixrieseberg** [comment]
This seems like a different issue - you're appearing to be using a native module, but recompilation fails due to a lack of node-gyp.

`npm i -g node-gyp` should help!
