### ISSUE TITLE
Upgrade to Electron 1.1.x (or 1.2.x)

### ISSUE THREAD

**Issue by frederikbosch** [felixrieseberg/ember-electron#67]
While building on Ubuntu 16.04 I receive the following error: `error while loading shared libraries: libnotify.so.4`. This seems to be fixed since [the issue for this problem was closed 14 days ago](https://github.com/electron/electron/issues/5348). The fix supposed to be in [Electron version 1.1.1](https://github.com/electron/electron/releases). That tells me that this package is not using that version. Is it a problem to upgrade?

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! You can always upgrade the version of Electron used - in fact, it's added as a dependency to your project. Look for `electron-prebuilt`. To upgrade, run:

```
npm install electron-prebuilt@1.2.1 --save
```
