### ISSUE TITLE
Differences between packaged and developed application?

### ISSUE THREAD

**Issue by nwestbury** [felixrieseberg/ember-electron#68]
This is likely not an issue but rather just a case of a newbie.

I wrote a simple ember login screen and it appears to work fine when I run it with `ember electron`. However when I package the app with `ember electrion:package`, I lose all CSS styling, the menu bar, and the developer console so I can't even see what's missing. The form logic still works . 

I suspected I'm just including some packages in my package.json but this doesn't explain why the menu bar options would be missing (I don't think...). Any ideas on a way I could debug the problem? Thanks!

Screenshots included for clarity and eye candy.

![Screenshot good](http://s33.postimg.org/9a5nwviwf/Screenshot_from_2016_06_02_02_28_01.png)

![Screenshot bad](http://s33.postimg.org/6eskq0ewf/Screenshot_from_2016_06_02_02_26_55.png)

**Comment by felixrieseberg** [comment]
Hey,

 * There is a default menu bar if you run your app with `electron` that is not visible after publishing. For more info, see [the docs](http://electron.atom.io/docs/api/menu/)
 * The developer console (specifically, the shortcut that opens it) is also part of the menu. For debugging without adding a developer console, you can call `require('remote').getCurrentWindow().toggleDevTools()`
* I'm not sure about your CSS. Are you setting the paths correctly?

**Comment by nwestbury** [comment]
@felixrieseberg Thank for your help! With the console I was able to identify the error (it was https://github.com/miguelcobain/ember-paper/issues/224 if you're curious). Kinda confusing for me that there is different behaviour from development to production but good to keep in mind.
