### ISSUE TITLE
Error: spawn wine ENOENT

### ISSUE THREAD

**Issue by GiovanniL19** [felixrieseberg/ember-electron#69]
When trying to package an ember project using `ember electron:package` I get the following error:

```
Error: spawn wine ENOENT
spawn wine ENOENT
Error: spawn wine ENOENT
    at exports._errnoException (util.js:890:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
```

Does anyone have any ideas why this is happening on my Mac?

**Comment by brzpegasus** [comment]
You need to install Wine in order to package for Windows from your Mac (the packaging command attempts to package for all platforms by default).

**Comment by GiovanniL19** [comment]
@brzpegasus Thank you, I will install that in a bit. I'm specifying a platform with `win32` and getting the following error:

<img width="771" alt="screen shot 2016-06-12 at 14 14 45" src="https://cloud.githubusercontent.com/assets/10454722/15991337/0cea7032-30a8-11e6-883d-9a7db87934a4.png">

Do I have to be on a windows PC to build? 

The command I am using is `ember electron:package --platform=win32`

**Comment by brzpegasus** [comment]
You may need to specify a version with the command, e.g. `ember electron:package --platform=win32 --version=1.2.2` to match one of the downloadables from this [list](https://github.com/electron/electron/releases).

**Comment by felixrieseberg** [comment]
Erstelle is totally right. You should also check your package.json - there should be a reference to your Electron version in there.

**Comment by felixrieseberg** [comment]
(closing for now)

**Comment by GiovanniL19** [comment]
Thank you both @brettchalupa and @felixrieseberg It is all working now!!! 

P.s ember-electron is amazing, thanks for all the hard work on this project :)
