### ISSUE TITLE
Failed to load local and remote assets

### ISSUE THREAD

**Issue by benoror** [felixrieseberg/ember-electron#70]
Hi @felixrieseberg! Before all kudos for such great addon and effort to bring Ember to the desktop 👍 😄 

Currently I am converting an existing Ember web app to a desktop using this addon, unfortunately I got stuck with some issues. When I run `ember electron` I got my app running, but some **remote** and **local** assets fail loading. If I open dev tools inside the app I get the following errors:

<img width="650" alt="screen shot 2016-06-22 at 13 47 11" src="https://cloud.githubusercontent.com/assets/119117/16279258/e5a7f5aa-387f-11e6-81c3-5f6a3f14c344.png">

I get this output in the console:

<img width="832" alt="screen shot 2016-06-22 at 13 46 43" src="https://cloud.githubusercontent.com/assets/119117/16279240/ce990a52-387f-11e6-8b84-db6b83da050c.png">

> *Note: Opening inspector in `http://localhost:30820` won't work

I tried these approaches unsuccessfully:

- Setting `locationType` to `'hash'`
- Placing `<base href="./">` inside my **index.html** ([link](http://stackoverflow.com/questions/37622389/electronjs-with-angular2-using-angular-cli-unable-to-locate-vendor-files/37663447#37663447))
- Removing/setting `baseUrl` to `'./'` in config ([link](https://github.com/usecanvas/ember-electron#notes))

Any hint would be really appreciated, thanks in advance!

Cheers!

**Comment by felixrieseberg** [comment]
Hey, thanks for reporting! 

Let's start with remote assets: You're probably referencing them using `///`, which is a shortcut for the current protocol (which in your case on Electron will be `file://`. Replace that with your actual protocol (or bake the files in - a CDN doesn't really help with a desktop app 😉 )

Local assets *should* work. However, if they are not part of the `dist` folder, you have to specify that you'd like to copy them manually in the `ember-electron` section of your package.json, like so:

```
"ember-electron": {
  "copy-files": [
    "package.json",
    "electron.js"
    "main/*"
  ],
}
```

**Comment by benoror** [comment]
Hey! awesome @felixrieseberg, thanks for your quick response!!! 👌 👍 

I already figured out the local assets issue by fixing some paths manually. Regarding the remote files the app was indeed using the `//` shortcut. I hope this helps others in the same situation

Also, you're totally right regarding CDN's, all assets should be baked & deployed in the same build, we still have a long road to make the experience fully desktop-like (offline storage, service workers, etc...)

PS: Are you aware of the inspector problem? Should I open another issue?

Thanks again and kind regards!
