### ISSUE TITLE
Several shortcuts (reload, toggle full screen, toggle dev tools) stop working in packaged binary

### ISSUE THREAD

**Issue by holandes22** [felixrieseberg/ember-electron#75]
Hi

I noticed that shortcuts work on dev but stop working on prod. Shortcuts like ctrl+R (reload) and F11 (toggle full screen) and Ctrl+shift+I (toggle dev tools ). 

I thought maybe the problem was on electron-packager so I cloned `electron-quick-start` and package it but all works as expected there, that is shortcuts continue working in the package.

To reproduce:

1. ember new myapp
2. cd myapp
3. ember install ember-electron
4. ember electron -> verify F11, Ctrl+R, Ctrl+Shift+I work
5. ember electron:package -> run the executable, shortcuts stop working

I tested with version 1.7.1 and ember-cli 2.6.2.

I'm on Arch Linux 64 bit, but also built package for Mac on travis and for Windows on appveyor and the problem still occurs on those platforms.

Not sure, but this might be related to the other ticket I opened #71

**Comment by felixrieseberg** [comment]
Quick question: Are you adding the shortcuts yourself (via `menu`)? Electron adds some default shortcuts in development mode, but doesn't in production mode. To be clear, that's an electron thing, not an ember-electron thing.

For more info, check out the docs over at electron/electron: https://github.com/electron/electron/blob/master/docs/api/menu.md

**Comment by holandes22** [comment]
No, didn't add any menu code at all to reproduce this, I'm referring to shortcuts that work out of the box in electron. 

For example if you clone the __electron-quick-start__ repo and run `npm start` you get _F11_  working. This keeps working after packaging it with electron-packager. But with ember-electron shortcuts only work when running `ember electron` but not after running `ember electron:package`. Again, talking about fresh projects in both cases

Sorry if I wasn't clear, and I apologize if this is to be expected, but I didn't find any docs on this and it is weird that ember-electron behaves differently than a regular electron app in this regard

**Comment by felixrieseberg** [comment]
Hey, apologies that this is so confusing (we in the Electron team should probably do something about that), but as soon as you package your application, there is no standard menu. The menu is the source for all keyboard shortcuts. Unless you add a menu yourself, no shortcuts (not even Copy/Paste) will work. F11 is probably activated from the dev tools, which open automatically in the quick-start.

Ember-Electron isn't different, it's just wrapping electron-packager. There are no docs (yet), [but this is exactly how it's supposed to work (even if that's weird)](https://github.com/electron/electron/issues/3787#issuecomment-164334741).

I'll make sure to add that information to the docs over at Electron.

**Comment by holandes22** [comment]
Thank you! I couldn't understand why it was working on quick-start. As you say, once I remove from quick-start the line to open the devtools, F11 et al stopped working.

Thanks again for pointing me in the right direction!

**Comment by kevingelion** [comment]
I'm experiencing issues of even setting the application menu in my app after packaging. Everything works as expected running `ember electron` but after packaging, the menu items with base roles like `edit` or `copy` are blank and return nothing in the menus. Might be related?

**Comment by felixrieseberg** [comment]
Do you have a repro? This is likely an issue with your code (or a bug in Electron), since `ember-electron` doesn't touch any of that stuff.
