### ISSUE TITLE
Can't import ipc module

### ISSUE THREAD

**Issue by timmyomahony** [felixrieseberg/ember-electron#76]
OK, I'm very new with electron so this may be a very basic question, but I want to import the `ipc` module in one of my Ember controllers so that I can tell the app to quit when I hit `esc`:

```
/* global require, Mousetrap */

import Ember from 'ember';

// I've tried both these
const ipc = require('ipc');
const ipc = requireNode('ipc');

export default Ember.Controller.extend({
  init() {
    this._super(...arguments);
    Mousetrap.bind('esc', function(){
      ipc.send('close-main-window');
    });
  },
  willDestroy() {
    Mousetrap.unbind('esc');
  }
});
```

but it's throwing an error in the console:

`ember.debug.js:31387Error: Cannot find module 'my-app/pods/application/controller'`

**Comment by felixrieseberg** [comment]
If you check out the Electron documentation, you should see that you need to require Electron:

```
const {ipcRenderer} = require('electron');
console.log(ipcRenderer.sendSync('synchronous-message', 'ping')); // prints "pong"

ipcRenderer.on('asynchronous-reply', (event, arg) => {
  console.log(arg); // prints "pong"
});
ipcRenderer.send('asynchronous-message', 'ping');
```

To see this work, you'll need to require ipcMain in the main thread (electron.js):

```
const {ipcMain} = require('electron');
ipcMain.on('asynchronous-message', (event, arg) => {
  console.log(arg); // prints "ping"
  event.sender.send('asynchronous-reply', 'pong');
});

ipcMain.on('synchronous-message', (event, arg) => {
  console.log(arg); // prints "ping"
  event.returnValue = 'pong';
});
```

**Comment by timmyomahony** [comment]
Thanks a million Felix, I really appreciate the quick reply. That works perfectly now and I've a better understanding of how Electron works.

**Comment by akatov** [comment]
presumably we need to use `requireNode('electron')` inside the Ember app?

**Comment by felixrieseberg** [comment]
We actually monkeypatch require to try both Ember's as well as Node's require - it'll go with the right one 👍
