### ISSUE TITLE
Ember-Data best practices

### ISSUE THREAD

**Issue by hglattergotz** [felixrieseberg/ember-electron#8]
Hello,

Thanks for putting this addon together!

When writing an ember app with ember-data it would normally access a JSON-API compliant REST backend. When building this as an electron app, would I build that "backend" as an express server in electron (in electron.js)?
Or would I somehow write an ember-data adapter that accesses either the filesystem or a database directly?

I would prefer to keep the REST model, but am not sure if that is the right thing to do since there does not seem to be any information about packaging a REST backend inside of electron.

**Comment by felixrieseberg** [comment]
Sky's the limit :rocket:. Nothing keeps you from running a server, but the network overhead seems unnecessary. I'd personally use localstorage or indexdb, depending on the use case. Ember Data Adapters exist for both.

I'm closing this for now (because it's not really an ember-electron issue).

**Comment by hglattergotz** [comment]
Agreed, this is certainly not an issue. Just wanted to ask you a question :smile:
The internal REST api does seem strange, I guess that is why I was not able to find any information on it.

Thank you!

**Comment by hugoruscitti** [comment]
nw.js wiki site has some thoughts about separation of concerns in desktops applications, i think its usefull to electron applications too:

https://github.com/nwjs/nw.js/wiki/About-Node.js-server-side-script-in-nw.js
https://github.com/nwjs/nw.js/wiki/Save-persistent-data-in-app

**Comment by hglattergotz** [comment]
@hugoruscitti :thumbsup: thanks!
