### ISSUE TITLE
Call app.quit()

### ISSUE THREAD

**Issue by isakgrozny** [felixrieseberg/ember-electron#80]
How do I call app.quit() (to terminate the app) from a component or a controller? This:

```
const app = require('electron')
```

doesn't do anything. 

I'm very new to ember and electron both and I would be grateful for any pointers. Thank you!

**Comment by felixrieseberg** [comment]
Hey! The Ember app is running inside a BrowserWindow, meaning that you'll have to access the app using the remote - or use the `electron.js` to interact with Electron's main thread.
