### ISSUE TITLE
App cannot load js/css with default config of ember-cli 2.7

### ISSUE THREAD

**Issue by holandes22** [felixrieseberg/ember-electron#81]
Ember-cli deprecates baseURL and introduced rootURL.
When using the default ember-cli config of `rootURL: ''` (empty string), app fails to load as it is unable to load the the css and js vendor/app resources.

After fiddling a little I discovered that using `null` as value for rootURL fixes this. (not sure if this an ugly hack but seems to work fine)

Is there something that can be done from the addon or it just needs to documented?
Happy to open a PR if needed

**Comment by felixrieseberg** [comment]
Hey! Since you already did the hard work of figuring it out, I think you deserve the PR credits (we just need to update our [environment.js](https://github.com/felixrieseberg/ember-electron/blob/master/blueprints/ember-electron/files/config/environment.js) in the blueprint).

If you don't feel like making a PR, let me know and I'll get it fixed 👍

**Comment by holandes22** [comment]
Glad to! getting late here so I'll work on a PR tomorrow. Need to figure out how to change the blueprint  depending on the ember-cli version (I think the `locals` hook is probably the way to do that https://ember-cli.com/extending/#developing-addons-and-blueprints)

**Comment by holandes22** [comment]
@felixrieseberg I opened PR #83 to address this. I'm not so pleased with my solution so if you know of a better way to do a hash with the ember-cli template system, please let me know and I'll refactor it.

**Comment by felixrieseberg** [comment]
I think that's an excellent solution, thank you very much! I'll go ahead and merge it right now.

**Comment by holandes22** [comment]
Awesome, thank you!

**Comment by kdawgwilk** [comment]
This seemed to have fixed loading assets listed in index.html for example but still none of my assets used in .scss styles are loading.  Do I need to set a config somewhere that will give the rootURL to the rest of the places its needed?

**Comment by kynetiv** [comment]
I think I'm noticing something simiar to @kdawgwilk. I see a `<base href="/" />` being added to my index.html head tag. Removing the base tag fixes my broken image links.
