### ISSUE TITLE
How to access application lifecycle? 

### ISSUE THREAD

**Issue by mateodelnorte** [felixrieseberg/ember-electron#84]
I want to allow services within my application (ember services or not) to access events and application context about the electron app. 

Is there a way to hook into the ember-electron application context in this way? 

For instance, I want to have a global object which other services can listen to for events like `context.on('application.loaded', fn)` as well as to house an API for manipulating common functions in my app - from a single context object. 

Any suggestions?

**Comment by felixrieseberg** [comment]
You can always use the [Electron remote](https://github.com/electron/electron/blob/master/docs/api/remote.md) to communicate with the main thread or any other threads inside your application. Usually, the IPC is used to transmit such events.
