### ISSUE TITLE
Unexpected Token Illegal

### ISSUE THREAD

**Issue by dominiquecharlebois** [felixrieseberg/ember-electron#87]
<img width="504" alt="capture d ecran 2016-08-03 a 22 09 19" src="https://cloud.githubusercontent.com/assets/19155476/17391022/6eedab8a-59c7-11e6-9529-cd95c41ea51b.png">

appnamefolder/node_modules/ember-electron/lib/helpers/remote-debug-script.js

**Comment by acbabis** [comment]
It looks like someone used an ES6 template string and your interpreter didn't like it. What version of node are you using, and can you upgrade?

**Comment by felixrieseberg** [comment]
@acbabis seems to be totally right here. Can you quickly punch `node -v` into your terminal and tell us about the output?

**Comment by dominiquecharlebois** [comment]
I was using 4.x, I'm now using 6.3.1. 
Which Node version should I be using ?

Thanks for the quick feedback.

**Comment by felixrieseberg** [comment]
I'd recommend 6 - that's what the current version of Electron is using. I hope your problem is fixed now, so I'm closing this - but do let me know if I'm mistaken!

**Comment by dominiquecharlebois** [comment]
I'll try to do some more debugging, but yeah, same problem. Git cloning the repo.

**Comment by felixrieseberg** [comment]
Can you do me a favor and try the following: Start the Node repl by just typing `node` into your terminal and then copy and paste this:

```
function hi() { console.log(`1 + 1 is ${1+1}`) }; hi();
```

Would love to see the output. The error message you're getting is pretty clear, your Node seems to not understand what the "`" is supposed to be.

**Comment by dominiquecharlebois** [comment]
node
> function hi() { console.log(`1 + 1 is ${1+1}`) }; hi();
1 + 1 is 2
undefined
>

**Comment by dominiquecharlebois** [comment]
locationType: process.env.EMBER_CLI_ELECTRON ? 'hash' : 'auto',

Was the problem. 

Close/Fixed ?

**Comment by felixrieseberg** [comment]
Well I'm just happy your problem is fixed 😌
