### ISSUE TITLE
Silent or confuse exception caused by require function

### ISSUE THREAD

**Issue by hugoruscitti** [felixrieseberg/ember-electron#88]
Hi, i found a confuse error when one of my services failed to load, ember-electron overrides the require function but catch all the errors messages and hide 'em, and show another error instead (not related to my app).

This is an example of the hidden (or confuse) message error i get in electron:

![demohiddenerroronelectron 2016-08-04 16-22-44](https://cloud.githubusercontent.com/assets/99183/17415309/b10e8456-5a5f-11e6-91b9-dea1cea604f6.png)

The same application on chrome shows a better error message:

![demohiddenerroronelectron 2016-08-04 16-23-26](https://cloud.githubusercontent.com/assets/99183/17415319/c982f29c-5a5f-11e6-8614-8c9ec500f912.png)

If i change the `lib/resources/shim-footer.js` to show the original error message, [see this gist](https://gist.github.com/hugoruscitti/6eb2ab1898a05057314980d20d90e9c4/revisions), i get some close to ideal to me:

![demohiddenerroronelectron 2016-08-04 16-24-55](https://cloud.githubusercontent.com/assets/99183/17415381/05ff472a-5a60-11e6-9439-74b8b2927b9c.png)

It's possible to show the original error message in a better way?, can i work in a pull request for this?

PS: I make a simple application showing this error in https://github.com/hugoruscitti/demo-hidden-error-on-electron, note that running with 'ember electron' or 'ember serve' show different errors.

**Comment by felixrieseberg** [comment]
You're totally right. Let me check and fix this.
