### ISSUE TITLE
Ajax request send file:// as Origin what perform an error in backend requests

### ISSUE THREAD

**Issue by enrimr** [felixrieseberg/ember-electron#91]
When you are running an app using electron, it sends file:// as header Origin. So any backend will fail.

**Comment by felixrieseberg** [comment]
This is not actually a bug, but a security feature. You can enable it there by enabling `file://` protocols. Client-side, you could either disable `web-security` or use [a custom protocol for your backend](https://github.com/electron/electron/blob/master/docs/api/protocol.md).
