### ISSUE TITLE
Command "ember electron:test [--server]" fails to run

### ISSUE THREAD

**Issue by holandes22** [felixrieseberg/ember-electron#95]
Hi,

All of the sudden I'm not able to run tests anymore with the `ember electron:test` command.

I'm getting the following error:

![error](https://cloud.githubusercontent.com/assets/510233/18417306/6348dc7e-7834-11e6-991a-559e4a9521a7.png)

As you can see the command exits with 1 (no error message is shown anywhere)

If I try to run that command manually, it works withou any issue (even auto-reloading works when saving files).

![cli](https://cloud.githubusercontent.com/assets/510233/18417314/9e63afe6-7834-11e6-93db-d4303b5237d8.png)
 
Was able to repro with a clean project as well.

This is most likely an issue with my system (Arch Linux, node 6.3) as I didn't touch any dependencies of my project, but I did a system upgrade at some point. Problem is, I have no clue of why it stopped working. Anybody ran into something similar? Any ideas how to debug?

**Comment by drewchandler** [comment]
This happens to me on OSX in a clean project as well.

In the app we've been developing, the tests stopped working after I did a nombom, so I think it must be related to a dependency.

After my tests stopped working, I had a co-worker generate a shrinkwrap on his machine where the tests were still working. Here is a link to a diff between his working shrinkwrap and by broken one: https://gist.github.com/drewchandler/4edd708c15f6ae2973b6ab93849721dd

Please let me know if there is anymore info I can provide.

**Comment by holandes22** [comment]
I recall doing a nombom to try an upgrade to latest ember (2.8), so when the test runner failed I assumed it was due to the upgrade. I then reverted the changes but the test runner continued to fail in the same way (then I tried in a clean project and same failure).

@drewchandler I mentioned above that I was able to run successfully the failed command in a different bash session, I wonder if you were able to do the same

**Comment by gitmitch** [comment]
I am also having this problem. I just started my first project using ember-electron, so it's a clean project. Unlike @holandes22 , I'm not able to run the command manually and get it to work.

ember electron:test --server output:
![image](https://cloud.githubusercontent.com/assets/13812739/18809296/7f0bf3fe-822c-11e6-8424-964eb30ea25e.png)

running the command manually and opening the dev tools in the window that opens:

![image](https://cloud.githubusercontent.com/assets/13812739/18809301/94c53214-822c-11e6-9cd1-6d991ea47718.png)

![image](https://cloud.githubusercontent.com/assets/13812739/18809303/9e922202-822c-11e6-9f00-050804ace507.png)

I looked at the contents of that tmp directory, and there is no dist sub-directory:

![image](https://cloud.githubusercontent.com/assets/13812739/18809307/b25d8c7c-822c-11e6-82d4-c2767abd3431.png)

I'm still pretty new to ember and electron, so I don't know what to try next for troubleshooting. Looks like there is supposed to be a build in dist? Or something else is wrong?

**Comment by holandes22** [comment]
@gitmitch two things I didn't mention for the command to work.
- make sure to set the envar EMBER_ENV to "test" when running the command
- run `ember electron:test --server` and leave it running, then in another shell run the command manually (on exit electron:test removes the temporary build used for the test so that is why you cannot find the path)

**Comment by gitmitch** [comment]
thanks, @holandes22 , i wasn't setting the EMBER_ENV variable. doing so allows me to employ the workaround.

**Comment by felixrieseberg** [comment]
Hey everyone, sorry that you're all having trouble - I'm not quite sure where to start, but sometimes just upgrading dependencies helps us out. I'll take a look today.

**Comment by makepanic** [comment]
I think i found the issue:
Testem >`1.10.4` serves jasmine test html.
Could you try to see if using `testem@1.10.4` fixes the issue for you? 
(`rm -rf node_modules/testem && npm i testem@1.10.4`)

**Comment by makepanic** [comment]
I found out what's causing the issue with testem > `1.10.4`:
They [moved to `spawn-args`](https://github.com/testem/testem/compare/v1.10.4...v1.11.0#diff-a820f5c6c04aaa2f94633dc30c9fc4eaR9) to parse the incoming args and [spawn them later](https://github.com/testem/testem/blob/master/lib/process-ctl.js#L48).
Ember-electrons test task [creates the spawn args](https://github.com/felixrieseberg/ember-electron/blob/master/lib/commands/electron-test/task.js#L37) by doing `'--option="' + value + '"'`.
If this input is put into the `spawn-args` method, it returns:

```js
[ '/path/ember-hearth/node_modules/ember-electron/lib/commands/electron-test/runner-ci.js',
  '--electron-path=',
  '/path/ember-hearth/node_modules/electron-prebuilt/dist/electron',
  '--tests-path=',
  '/path/ember-hearth/tmp/core_object-tests_dist_electron-26BgIvx0.tmp/tests' ]
```

which isn't really a valid argument for spawning something in node.
If we change the test tasks `electronCommand` and remove the equals sign like:

```js
'--electron-path ' + safePath(findElectron(this.project))
```

(same for `--tests-path`) , it'll return:

```js
[ '/path/ember-hearth/node_modules/ember-electron/lib/commands/electron-test/runner-ci.js',
  '--electron-path',
  '/path/ember-hearth/node_modules/electron-prebuilt/dist/electron',
  '--tests-path',
  '/path/ember-hearth/tmp/core_object-tests_dist_electron-AO87yhsg.tmp/tests' ]
```

which is correct and runs the tests as expected.


https://github.com/testem/testem/blob/master/lib/process-ctl.js#L48

@felixrieseberg If this fix is ok, I could open a PR

**Comment by felixrieseberg** [comment]
@makepanic Excellent work, thank you soooo much! A PR would be most appreciated 👏

**Comment by holandes22** [comment]
Works great, thank you!
