### ISSUE TITLE
DEPRECATION: `baseURL` vs `rootURL`

### ISSUE THREAD

**Issue by oskarrough** [felixrieseberg/ember-electron#96]
Hi, I'm getting the following message on a clean ember-cli 2.8.0 with ember-electron 1.8.5.

`DEPRECATION: Using the `baseURL` setting is deprecated, use `rootURL` instead.`

Perhaps this is related to either https://github.com/felixrieseberg/ember-electron/commit/b6a687e2907da80bf7f1eb1da48434b374879aaf? or https://github.com/felixrieseberg/ember-electron/blob/master/config/environment.js#L7

**Comment by felixrieseberg** [comment]
This should already be closed - if Ember Cli is above 2.7, it'll set rootURL.

**Comment by oskarrough** [comment]
Hm, I just tried a new

```
ember new just-a-test
ember install ember-electron
```

with ember-cli 2.8.0 and it still gives me the deprecation noted above. Installing the addon sets the `rootURL` to `null` in config/environment.js - is that on purpose? Resetting it to `/` doesn't solve the deprecation either.

**Comment by felixrieseberg** [comment]
🤔 Seems like I was too eager, thanks for double checking.

**Comment by anulman** [comment]
@felixrieseberg resolved? Else it may be better to focus on efforts on a PR that validates ember config & offers instructive error msgs, vs (over)writes values on install

**Comment by bendemboski** [comment]
I can double-check when I have time, but I'm pretty sure #120 will address this.

**Comment by bendemboski** [comment]
Oh wait, I'm confusing this with some test-related baseURL/rootURL stuff -- I don't think my changes will fix this.

**Comment by anulman** [comment]
Nope! But #120 was 👍 too

**Comment by pichfl** [comment]
I think #156 can solve this as well.

**Comment by anulman** [comment]
Yeah! I like your solution much better than the validations.

Will leave this one open until that lands to confirm though, if that's all right :)

**Comment by anulman** [comment]
Closing because people have seen this working in #156
