### ISSUE TITLE
Ability to customise browser window options

### ISSUE THREAD

**Issue by mz2** [felixrieseberg/ember-electron#97]
I'm not 100% sure if this is a feature request or me exposing my lack of understanding of ember-electron: I would like the ability to customise the options such as `webPreferences` used when windows are launched in my ember-electron application. I can't find a way of doing this at the moment without modifying the ember-electron package itself.

**Comment by felixrieseberg** [comment]
You absolutely can - `ember-electron` puts an `electron.js` file into your repo, which is exactly what you're looking for. You can even customize everything about it to your hearts content!
